# C题问题二：日前购电—日内因果储能融合模型及消融实验

本 Notebook 是现有 Q2 的增量补充，不覆盖正式 `result2.xlsx`，也不删除已有预测消融和 P0—P6 规划实验。它重点修正原模型中“每天 0:00 同时固定全天购电和全部储能动作、每天实际 SOC 强制回到 6000 kWh”的偏强假设。

信息时序为：每天 0:00 只锁定全天计划购电量与参考 SOC；每个 10 分钟时槽开始后，只使用当前已经观测到的实际净负荷和实际 SOC 决定充电、放电、弃电和紧急购电。任何函数都不得读取后续时槽的真实值。

## 1. 问题分析与模型选择

日前购电单价已知，临时购电单价是同一时槽正常电价的 5 倍。只使用点预测会低估误差尾部，只使用完全固定的两阶段 SAA 又限制了储能的实时纠偏能力。因此本节将“日前不可撤销决策”和“日内可适应决策”分离：

- 日前变量：$q_{d,t}$，即计划购电量；
- 日内变量：$c_{d,t},v_{d,t},z_{d,t},s_{d,t}$，分别为充电、放电、紧急购电和弃电；
- 状态变量：$E_{d,t}$，为储能电量；
- 参考变量：$E^{\rm ref}_{d,t}$，由日初 LP 给出，只用于构造保留线，不等于实际 SOC。

在预测曲线给定时，目标函数、功率平衡、SOC 递推、功率和容量边界均为线性，因此日初问题使用 LP，可以直接获得有限模型的全局最优解。GA、PSO 不会提高线性模型的最优性证明；LSTM 等方法属于预测端，也不能代替规划端的可行性约束。

## 2. 单位、物理约束与参数来源

附件数据为功率 kW，采样间隔为 $\Delta t=1/6$ h。所有规划和执行变量使用 kWh：

$$N_{d,t}=\Delta t(L_{d,t}-P_{d,t}).$$

题目物理参数固定为：容量 12000 kWh，保护区间 $[1200,10800]$ kWh，最大充放电功率 5000 kW，即每槽上限 $5000/6$ kWh，充放电效率均为 0.9。紧急购电倍率 5 来自题意。

统计参数不是随意给定：残差窗口 14/21/28/42/56 天对应 2/3/4/6/8 个完整周；$\alpha$ 先在 $[0.50,0.95]$ 上以 0.05 粗搜，再在局部以 0.01 细搜；$\rho\in\{0,0.25,0.5,0.75,1\}$ 覆盖完全灵活到完全跟随参考库存；0/3/5 槽平滑用于检验局部分位数噪声，其中三点核为 $(1,2,1)/4$，五点核为 $(1,4,6,4,1)/16$，均为对称且归一化的二项式核，不引入相位移动。每月配置仅由月初之前 56 个已结束日期选择，11—12 月冻结 10 月规则。

$\alpha=0.8$ 仅是经济学锚点。在忽略储能和跨时槽耦合的单时槽问题

$$\min_q\;p_tq+5p_t\,\mathbb E[(N_t-q)_+]$$

中，临界分位数满足 $F_N(q)=1-p_t/(5p_t)=0.8$。完整系统存在 SOC 耦合，因此最终 $\alpha$ 必须由历史端到端成本选择，不能预先宣称 0.8 最优。

## 3. 日初参考规划 LP

对点预测、残差分位预测或条件残差分位预测得到的风险净负荷 $\widetilde N_{d,t}$，求解

$$\min \sum_{t=1}^{144}p_tq_{d,t},$$

满足

$$q_{d,t}+v^{\rm ref}_{d,t}-c^{\rm ref}_{d,t}-s^{\rm ref}_{d,t}=\widetilde N_{d,t},$$

$$E^{\rm ref}_{d,t+1}=E^{\rm ref}_{d,t}+\eta_c c^{\rm ref}_{d,t}-\frac{v^{\rm ref}_{d,t}}{\eta_d},$$

$$1200\le E^{\rm ref}_{d,t}\le10800,$$

$$0\le c^{\rm ref}_{d,t},v^{\rm ref}_{d,t}\le5000/6,$$

$$q_{d,t},s^{\rm ref}_{d,t}\ge0.$$

参考轨迹日末取 6000 kWh，这是规划边界假设，不强迫真实执行日末回到 6000。实际 SOC 跨日传递。

## 4. 风险净负荷与日内因果执行

普通残差分位策略为

$$\widetilde N_{d,t}(\alpha,W)=\widehat N_{d,t}+Q_\alpha\{N_{j,t}-\widehat N_{j,t}:d-W\le j<d\}.$$

条件策略从过去最多 120 天中，依次使用季节周期、星期周期及预测负荷/光伏日总电量选择相似日；候选特征的尺度只用历史池估计。

日内保留线定义为

$$R_{d,t}(\rho)=E_{\min}+\rho(E^{\rm ref}_{d,t+1}-E_{\min}).$$

若计划购电高于当前实际净负荷，则在功率和容量范围内充电，剩余弃电；若出现缺口，则

$$v_{d,t}=\min\{-\delta_{d,t},P_{\max}\Delta t,
\eta_d[E_{d,t}-R_{d,t}(\rho)]_+\},$$

$$z_{d,t}=-\delta_{d,t}-v_{d,t},$$

其中 $\delta_{d,t}=q_{d,t}-N_{d,t}$。紧急电量只补当前供电缺口，不用于事后给电池充电。

## 5. H0—H5 机制消融

|编号|模型|唯一主要变化|回答的问题|
|---|---|---|---|
|H0|原加权 SAA 固定执行|购电和储能动作均在日初锁定，日循环 SOC|旧模型基准|
|H1-fixedQ|沿用 H0 的购电与参考轨迹，改为因果执行|只改变执行权限|日内纠偏的价值|
|H1-replan|SAA 按实际日初 SOC 重算参考计划|再加入跨日状态反馈|连续 SOC 的价值|
|H2|点预测 LP + 因果执行|不加残差安全余量|不确定性建模是否必要|
|H3|残差分位 LP + 因果执行|学习 $\alpha,W,\rho$ 与平滑|主要融合候选|
|H4|条件残差分位 LP + 因果执行|相似日替代纯时间窗口|条件选场景是否有用|
|H5|使用真实净负荷的连续期 Oracle LP|完美信息|理论下界与预测价值空间|

H0 与 H1-fixedQ 使用相同的 $q$，用于识别执行灵活性的贡献。H2—H4 共用同一个因果执行器，防止把执行差异误归因于预测风险模型。H5 为每个策略匹配其实际年末 SOC；另报告库存修正成本，不制造在线策略必能精确回到 6000 的假象。

## 6. 评价体系与验收规则

经济指标包括计划费、紧急费、总成本、计划与紧急购电量、弃电量、紧急时槽/日期/事件频率、日成本 CVaR$_{90}$/CVaR$_{95}$、最大日成本、最终 SOC、库存修正成本和 Oracle 差距。

库存修正成本为

$$C_{\rm adj}=C_{\rm actual}-\frac{p_{\min}}{\eta_c}(E_{\rm end}-E_{\rm start}).$$

该指标只用于校正不同年末库存，不替代真实支付账单。采用 7 日移动块 Bootstrap、2000 次、随机种子 2026 计算日成本差的 95% 区间。开发期为 6—10 月；11—12 月只检查 10 月冻结规则。差异小于 0.1% 时优先理论锚点附近、较短窗口和更简单结构。

逐时检查功率平衡、SOC 递推、容量和功率边界、非负性与同时充放电；LP 还检查原始矩阵残差和对偶间隙。因果性通过“任意扰动未来实际值，当前以前动作保持不变”的前缀测试验证。

## 7. 完整可复现模型源码

下方单元格嵌入本次实际运行的全部模型源码，避免 Notebook 文字、公式与外部脚本版本不一致。

In [ ]:
from pathlib import Path
import sys
PROJECT_ROOT = Path('/content/CUMCM_2026_Last_Dance') if Path('/content/CUMCM_2026_Last_Dance').exists() else Path.cwd().parent
if str(PROJECT_ROOT / 'code') not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT / 'code'))
print('PROJECT_ROOT =', PROJECT_ROOT)

PROJECT_ROOT = /content/CUMCM_2026_Last_Dance

In [ ]:
"""Q2 融合规划实验：日前购电计划 + 日内因果储能执行。

本模块不覆盖正式 result2.xlsx，也不修改原 q2_planning.py。功率输入为 kW，
进入优化与执行前统一乘 DT 转换为每个 10 分钟时槽的 kWh。
"""
from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
import hashlib
import json
import os
import time
import warnings

import numpy as np
import pandas as pd
from scipy.ndimage import gaussian_filter1d
from scipy.optimize import linprog
from scipy.sparse import coo_matrix

from q2_planning import (CAP, DT, ETA, HI, INITIAL, LO, SEED, T, Study,
                         atom_json, bootstrap, cvar, file_hash, weights_for)


ALPHA_COARSE = np.round(np.arange(.50, .951, .05), 2)
RHO_GRID = np.array([0., .25, .5, .75, 1.])
WINDOW_GRID = np.array([14, 21, 28, 42, 56])
SMOOTH_GRID = np.array([0, 3, 5])
K_GRID = np.array([14, 21, 28, 42])
FEATURE_GRID = ("season", "weekday", "level")
DEFAULT = {"alpha": .8, "rho": .5, "window": 28, "smooth": 3}
TOL = 1e-6


def _ridge(x, y, weights, penalties):
    """队友方案中的多输出加权岭回归原式。"""
    y = np.asarray(y, float)
    flat = y.ndim == 1
    if flat:
        y = y[:, None]
    gram = x.T @ (weights[:, None] * x) + np.diag(penalties)
    beta = np.linalg.solve(gram, x.T @ (weights[:, None] * y))
    return beta[:, 0] if flat else beta


def _softmax_weights(errors, decay):
    e = np.asarray(errors, float)
    e = e / max(float(e.mean()), 1e-9)
    w = np.exp(-decay * e)
    return w / w.sum()


def _team_load_weekly(hist):
    if len(hist) < 7:
        return hist.mean(axis=0)
    out = hist[-7].copy()
    if len(hist) >= 14:
        ratio = hist[-7:].mean() / max(hist[-14:-7].mean(), 1e-9)
        out *= np.clip(ratio, .85, 1.15)
    return out


def _team_load_trend(hist, dates, target, window=28):
    m = min(len(dates), window)
    dd = dates[-m:]
    lag = np.array([(d - target).days for d in dd], float)
    weekday = np.array([d.weekday() for d in dd])
    x = np.column_stack([np.ones(m), lag / 7,
                         *[(weekday == k).astype(float) for k in range(1, 7)]])
    target_x = np.array([1., 0., *[float(target.weekday() == k) for k in range(1, 7)]])
    beta = _ridge(x, hist[-m:], np.exp(lag / 14),
                  np.array([1e-8, .20, *([.05] * 6)]))
    return target_x @ beta


def _team_pv_physics(hist, shape_days=14, level_window=7,
                     shape_quantile=.9, threshold=.1, shrink=.5):
    recent = hist[-min(len(hist), shape_days):]
    ref = np.quantile(recent, shape_quantile, axis=0)
    peak = float(ref.max())
    if peak <= 1e-9:
        return hist[-min(len(hist), level_window):].mean(axis=0)
    mask = ref > threshold * peak
    if mask.sum() < 6:
        return hist[-min(len(hist), level_window):].mean(axis=0)
    k = np.array([day[mask].sum() / ref[mask].sum() for day in recent])
    level = min(len(k), max(4, 2 * level_window))
    kk = k[-level:]
    lag = np.arange(level) - (level - 1)
    tau = max(2., level / 3)
    x = np.column_stack([np.ones(level), lag])
    beta = _ridge(x, kk, np.exp(lag / tau), np.array([1e-8, .30]))
    estimate = (1 - shrink) * float(beta[0] + beta[1]) + shrink * float(
        np.average(kk, weights=np.exp(lag / tau)))
    out = np.clip(estimate, .05, 1.25) * ref
    out[~mask] = 0
    out[np.max(recent, axis=0) <= 0] = 0
    return np.minimum(np.maximum(out, 0), recent.max(axis=0) * 1.05)


def build_team_a_forecast(load, pv, dates):
    """忠实移植队友 OptimizedBank 的点预测层；所有切片严格止于 d-1。"""
    n = len(dates)
    load_members = np.full((2, n, T), np.nan)
    pv_members = np.full((3, n, T), np.nan)
    for d in range(1, n):
        hl, hp = load[:d], pv[:d]
        load_members[0, d] = _team_load_weekly(hl)
        load_members[1, d] = _team_load_trend(hl, dates[:d], dates[d], 28)
        pv_members[0, d] = hp[-min(5, d):].mean(axis=0)
        m = min(d, 28)
        lag = np.arange(m)[::-1]
        w = np.exp(-lag / 3.)
        pv_members[1, d] = (hp[-m:] * w[:, None]).sum(axis=0) / w.sum()
        pv_members[2, d] = _team_pv_physics(hp)
    wl = np.full((n, 2), .5)
    wp = np.full((n, 3), 1 / 3)
    for d in range(3, n):
        lo = max(1, d - 10)
        if d - lo < 2:
            continue
        el = np.array([np.mean(np.abs(load[lo:d] - load_members[k, lo:d])) for k in range(2)])
        ep = np.array([np.mean(np.abs(pv[lo:d] - pv_members[k, lo:d])) for k in range(3)])
        wl[d], wp[d] = _softmax_weights(el, 8.), _softmax_weights(ep, 8.)
    load_hat = np.einsum("knt,nk->nt", load_members, wl)
    pv_hat = np.einsum("knt,nk->nt", pv_members, wp)
    load_hat = np.maximum(gaussian_filter1d(load_hat, 1., axis=1, mode="nearest"), 0)
    pv_hat = np.maximum(gaussian_filter1d(pv_hat, 1., axis=1, mode="nearest"), 0)
    for d in range(1, n):
        pv_hat[d, np.max(pv[max(0, d - 14):d], axis=0) <= 0] = 0
    raw_net = (load_hat - pv_hat) * DT
    actual_net = (load - pv) * DT
    residual = actual_net - raw_net
    phi = np.zeros(n)
    for d in range(2, n):
        lo = max(1, d - 21)
        if d - lo < 3:
            continue
        prev, curr = residual[lo - 1:d - 1].ravel(), residual[lo:d].ravel()
        den = float(prev @ prev)
        if den > 1e-12:
            phi[d] = np.clip(float(prev @ curr / den), 0, .6)
    net = raw_net.copy()
    net[1:] += phi[1:, None] * np.nan_to_num(residual[:-1])
    # 将 AR 修正归入负荷端，仅为保持统一 load/pv/net 明细结构。
    load_hat += (net - raw_net) / DT
    return np.stack([np.maximum(load_hat, 0), np.maximum(pv_hat, 0)]), {
        "load_weights": wl, "pv_weights": wp, "phi": phi}


def smooth_margin(margin, width):
    if width == 0:
        return np.asarray(margin, float)
    # 3 槽沿用队友方案的三角核；5 槽使用其自然二项式扩展。
    # 两者均对称、权重和为 1，不会引入相位移动或改变日总残差均值。
    kernel = {3: np.array([1., 2., 1.]) / 4,
              5: np.array([1., 4., 6., 4., 1.]) / 16}[int(width)]
    pad_left = width // 2
    pad_right = width - 1 - pad_left
    return np.convolve(np.pad(margin, (pad_left, pad_right), mode="edge"), kernel, mode="valid")


def execute_causal(q, actual_net, initial_soc, reference_soc, rho):
    """逐槽执行器。函数签名中没有未来实际值，因而天然满足非前视约束。"""
    q, actual_net = np.asarray(q, float), np.asarray(actual_net, float)
    c = np.zeros(T); v = np.zeros(T); z = np.zeros(T); spill = np.zeros(T)
    soc = np.empty(T + 1); soc[0] = float(initial_soc)
    for t in range(T):
        surplus = q[t] - actual_net[t]
        if surplus >= 0:
            c[t] = min(surplus, CAP, max((HI - soc[t]) / ETA, 0))
            spill[t] = surplus - c[t]
        else:
            reserve = LO + rho * (reference_soc[t + 1] - LO)
            v[t] = min(-surplus, CAP, ETA * max(soc[t] - reserve, 0))
            z[t] = -surplus - v[t]
        soc[t + 1] = soc[t] + ETA * c[t] - v[t] / ETA
    return {"c": c, "v": v, "z": z, "spill": spill, "soc": soc}


def execution_checks(q, net, run):
    c, v, z, spill, soc = (run[k] for k in ["c", "v", "z", "spill", "soc"])
    balance = q + z + v - c - spill - net
    dynamics = np.diff(soc) - ETA * c + v / ETA
    checks = {
        "balance_residual": float(np.max(np.abs(balance))),
        "soc_recursion_residual": float(np.max(np.abs(dynamics))),
        "soc_min": float(soc.min()), "soc_max": float(soc.max()),
        "charge_max": float(c.max()), "discharge_max": float(v.max()),
        "negative_min": float(min(x.min() for x in [q, c, v, z, spill])),
        "simultaneous_max": float(np.minimum(c, v).max()),
    }
    checks["pass"] = bool(
        max(checks["balance_residual"], checks["soc_recursion_residual"]) <= TOL
        and checks["soc_min"] >= LO - TOL and checks["soc_max"] <= HI + TOL
        and max(checks["charge_max"], checks["discharge_max"]) <= CAP + TOL
        and checks["negative_min"] >= -TOL and checks["simultaneous_max"] <= TOL)
    return checks


@dataclass(frozen=True)
class PolicyConfig:
    alpha: float = .8
    rho: float = .5
    window: int = 28
    smooth: int = 3
    features: str = "level"
    k: int = 21


class HybridStudy:
    def __init__(self, root):
        self.root = Path(root)
        self.base = Study(self.root)
        self.price = self.base.price
        self.dates = self.base.dates
        self.load, self.pv, self.net = self.base.load, self.base.pv, self.base.net
        self.net_energy = self.net * DT
        # 修复原规划 Study 为兼容表临时写入真实值的冷启动：融合实验始终使用因果预测。
        ridge = self.base.fc["Ridge"].copy(); ridge[:, :90] = self.base.legacy[:, :90]
        team, self.team_diagnostics = build_team_a_forecast(self.load, self.pv, self.dates)
        self.fc = {"ManualWeekly": self.base.legacy.copy(), "Ridge": ridge, "TeamA": team}
        self.out = self.root / "results/q2_hybrid_v1"
        self.fig = self.root / "figures/q2_hybrid_v1"
        self.out.mkdir(parents=True, exist_ok=True); self.fig.mkdir(parents=True, exist_ok=True)
        source = file_hash(self.root / "code/q2_hybrid.py")
        self.fingerprint = hashlib.sha256((source + self.base.fingerprint).encode()).hexdigest()
        self.cache = self.out / "checkpoints" / self.fingerprint[:16]
        self.cache.mkdir(parents=True, exist_ok=True)
        self._plan_cache = {}
        self.progress("initialized")

    def progress(self, phase, **kwargs):
        payload = {"phase": phase, "utc": pd.Timestamp.now(tz="UTC").isoformat(),
                   "fingerprint": self.fingerprint, **kwargs}
        atom_json(self.out / "progress.json", payload)
        print(phase, kwargs, flush=True)

    def forecast_net(self, method, d):
        return (self.fc[method][0, d] - self.fc[method][1, d]) * DT

    def residual_pool(self, method, d, window):
        start = max(1, d - int(window))
        fc_hist = (self.fc[method][0, start:d] - self.fc[method][1, start:d]) * DT
        pool = self.net_energy[start:d] - fc_hist
        hist = np.arange(start, d)
        finite = np.isfinite(pool).all(axis=1)
        pool, hist = pool[finite], hist[finite]
        if len(pool) == 0 or not np.isfinite(pool).all():
            raise ValueError(f"残差池非法: method={method}, d={d}, W={window}")
        return pool, hist

    def conditional_pool(self, method, d, features, k):
        hist = np.arange(max(7, d - 120), d)
        dayofyear = self.dates.dayofyear.to_numpy()
        weekday = self.dates.dayofweek.to_numpy()
        fc = self.fc[method]
        x = np.column_stack([
            np.sin(2 * np.pi * dayofyear / 365), np.cos(2 * np.pi * dayofyear / 365),
            np.sin(2 * np.pi * weekday / 7), np.cos(2 * np.pi * weekday / 7),
            fc[0].sum(axis=1) * DT, fc[1].sum(axis=1) * DT])
        dims = {"season": 2, "weekday": 4, "level": 6}[features]
        scale = x[hist, :dims].std(axis=0); scale[scale < 1e-9] = 1
        dist = np.sum(((x[hist, :dims] - x[d, :dims]) / scale) ** 2, axis=1)
        chosen = np.sort(hist[np.argsort(dist, kind="stable")[:min(int(k), len(hist))]])
        fc_hist = (fc[0, chosen] - fc[1, chosen]) * DT
        return self.net_energy[chosen] - fc_hist, chosen

    def risk_net(self, method, d, cfg, conditional=False):
        if conditional:
            pool, hist = self.conditional_pool(method, d, cfg.features, cfg.k)
        else:
            pool, hist = self.residual_pool(method, d, cfg.window)
        margin = smooth_margin(np.quantile(pool, cfg.alpha, axis=0), cfg.smooth)
        return self.forecast_net(method, d) + margin, hist

    def solve_reference(self, net_energy, initial, terminal=INITIAL):
        """确定性日前 LP；严格保留队友基准的目标和平局处理以便费用回归。"""
        net_energy = np.asarray(net_energy, float)
        n = len(net_energy)
        row, col, value = [], [], []
        def add(r, c, v):
            row.append(r); col.append(c); value.append(v)
        for t in range(n):
            for block, coefficient in ((0, 1), (1, -1), (2, 1), (3, -1)):
                add(t, block * n + t, coefficient)
            add(n + t, 4 * n + t, 1)
            add(n + t, n + t, -ETA)
            add(n + t, 2 * n + t, 1 / ETA)
            if t:
                add(n + t, 4 * n + t - 1, -1)
        add(2 * n, 5 * n - 1, 1)
        A = coo_matrix((value, (row, col)), shape=(2 * n + 1, 5 * n)).tocsr()
        rhs = np.r_[net_energy, np.zeros(n), terminal]
        rhs[n] = initial
        objective = np.r_[self.price, np.zeros(4 * n)]
        bounds = ([(0, None)] * n + [(0, CAP)] * (2 * n) + [(0, None)] * n
                  + [(LO, HI)] * n)
        started = time.perf_counter()
        fit = linprog(objective, A_eq=A, b_eq=rhs, bounds=bounds,
                      method="highs", options={"presolve": True})
        seconds = time.perf_counter() - started
        if not fit.success:
            raise RuntimeError(fit.message)
        q, c, v, spill, soc_end = np.split(fit.x, 5)
        remove = np.minimum(c, v / ETA ** 2)
        c = c - remove; v = v - ETA ** 2 * remove
        spill = spill + (1 - ETA ** 2) * remove
        soc = np.r_[initial, soc_end]
        balance = q + v - c - spill - net_energy
        dynamics = np.diff(soc) - ETA * c + v / ETA
        if max(np.abs(balance).max(), np.abs(dynamics).max()) > 1e-5:
            raise AssertionError("reference LP back-substitution failed")
        return {"q": q, "c": c, "v": v, "spill": spill, "soc": soc,
                "seconds": seconds, "objective": float(self.price @ q)}

    def plan(self, method, d, family, cfg, initial, fixed_initial=False):
        plan_initial = INITIAL if fixed_initial else float(initial)
        cache_key = (method, int(d), family, cfg, round(plan_initial, 6))
        reusable = family == "saa" and fixed_initial
        if reusable and cache_key in self._plan_cache:
            return self._plan_cache[cache_key]
        if family == "point":
            scen, w, hist = self.forecast_net(method, d)[None, :], np.ones(1), np.array([], int)
        elif family == "quantile":
            risk, hist = self.risk_net(method, d, cfg)
            scen, w = risk[None, :], np.ones(1)
        elif family == "conditional":
            risk, hist = self.risk_net(method, d, cfg, conditional=True)
            scen, w = risk[None, :], np.ones(1)
        elif family == "saa":
            pool, hist = self.residual_pool(method, d, 21)
            scen = self.forecast_net(method, d)[None, :] + pool
            w = weights_for(len(pool), 14)
        else:
            raise KeyError(family)
        if family == "saa":
            sol = self.base.solve(scen / DT, w, initial=plan_initial, terminal=INITIAL)
        else:
            sol = self.solve_reference(scen[0], plan_initial, INITIAL)
        result = {**sol, "history": hist, "plan_initial": plan_initial}
        if reusable:
            self._plan_cache[cache_key] = result
        return result

    def _day_row(self, method, policy, d, sol, initial, fixed=False, rho=.5, keep_slots=False):
        if fixed:
            realized = self.base.realized(sol, self.net[d])
            run = {"c": sol["c"], "v": sol["v"],
                   "z": np.maximum(self.net_energy[d] + sol["c"] - sol["v"] - sol["q"], 0),
                   "spill": np.maximum(sol["q"] + sol["v"] - self.net_energy[d] - sol["c"], 0),
                   "soc": sol["soc"]}
            checks = execution_checks(sol["q"], self.net_energy[d], run)
            terminal = float(sol["soc"][-1])
        else:
            run = execute_causal(sol["q"], self.net_energy[d], initial, sol["soc"], rho)
            checks = execution_checks(sol["q"], self.net_energy[d], run)
            if not checks["pass"]:
                raise AssertionError(checks)
            z, spill = run["z"], run["spill"]
            realized = {
                "planned_cost": float(self.price @ sol["q"]),
                "emergency_cost": float(5 * self.price @ z),
                "total_cost": float(self.price @ sol["q"] + 5 * self.price @ z),
                "planned_kwh": float(sol["q"].sum()), "emergency_kwh": float(z.sum()),
                "spill_kwh": float(spill.sum()), "charge_kwh": float(run["c"].sum()),
                "discharge_kwh": float(run["v"].sum()),
                "emergency_slots": int((z > TOL).sum()),
                "emergency_day": int((z > TOL).any()),
                "events": int(((z > TOL) & ~np.r_[False, z[:-1] > TOL]).sum()),
                "peak_price_emergency_kwh": float(z[self.price >= np.quantile(self.price, .75)].sum()),
            }
            terminal = float(run["soc"][-1])
        row = {"method": method, "policy": policy, "d": int(d),
               "date": str(self.dates[d].date()), "initial_soc": float(initial),
               "terminal_soc": terminal, "rho": float(rho),
               "max_history_day": int(sol["history"].max()) if len(sol["history"]) else d - 1,
               "solve_seconds": float(sol["seconds"]), **realized, **checks}
        slots = None
        if keep_slots:
            slots = pd.DataFrame({"method": method, "policy": policy, "date": row["date"],
                "slot": np.arange(T), "price": self.price, "net_actual_kwh": self.net_energy[d],
                "q": sol["q"], "c": run["c"], "v": run["v"], "z": run["z"],
                "spill": run["spill"], "soc_start": run["soc"][:-1],
                "soc_end": run["soc"][1:], "reference_soc_end": sol["soc"][1:]})
        return row, slots

    def simulate(self, method, policy, start, stop, config_for_day=None,
                 constant=None, keep_slots=False, initial=INITIAL):
        rows, slots = [], []
        soc = float(initial)
        for d in range(int(start), int(stop)):
            cfg = constant if constant is not None else config_for_day(d)
            if cfg is None:
                cfg = PolicyConfig(**DEFAULT)
            if policy == "H0_fixed_SAA":
                sol = self.plan(method, d, "saa", cfg, INITIAL, fixed_initial=True)
                row, detail = self._day_row(method, policy, d, sol, INITIAL, fixed=True)
                soc = INITIAL
            elif policy == "H1_fixedQ_causal":
                sol = self.plan(method, d, "saa", cfg, INITIAL, fixed_initial=True)
                row, detail = self._day_row(method, policy, d, sol, soc, rho=cfg.rho,
                                            keep_slots=keep_slots)
                soc = row["terminal_soc"]
            else:
                family = {"H1_replan_SAA": "saa", "H2_point": "point",
                          "H3_quantile": "quantile", "H4_conditional": "conditional"}[policy]
                sol = self.plan(method, d, family, cfg, soc)
                row, detail = self._day_row(method, policy, d, sol, soc, rho=cfg.rho,
                                            keep_slots=keep_slots)
                soc = row["terminal_soc"]
            row.update({"alpha": cfg.alpha, "window": cfg.window, "smooth": cfg.smooth,
                        "features": cfg.features, "k": cfg.k})
            rows.append(row)
            if detail is not None:
                slots.append(detail)
        return pd.DataFrame(rows), (pd.concat(slots, ignore_index=True) if slots else None)


def inventory_adjusted_cost(frame, price_min):
    return float(frame.total_cost.sum() - price_min / ETA *
                 (frame.iloc[-1].terminal_soc - frame.iloc[0].initial_soc))


def choose_near(scores, keys):
    best = scores.score.min()
    near = scores[scores.score <= best * 1.001].copy()
    near["tie"] = list(zip(*[near[k] for k in keys]))
    return near.sort_values(["tie", "score"]).iloc[0]


def _score_configs(s, method, policy, origin, configs, stage):
    records = []
    for j, cfg in enumerate(configs):
        frame, _ = s.simulate(method, policy, origin - 56, origin, constant=cfg)
        records.append({"method": method, "month": s.dates[origin].month,
                        "origin": str(s.dates[origin].date()), "stage": stage,
                        **cfg.__dict__, "score": inventory_adjusted_cost(frame, s.price.min()),
                        "raw_cost": float(frame.total_cost.sum()),
                        "terminal_soc": float(frame.iloc[-1].terminal_soc)})
        if (j + 1) % 20 == 0:
            s.progress("selection_progress", method=method, month=s.dates[origin].month,
                       stage=stage, done=j + 1, total=len(configs))
    return pd.DataFrame(records)


def select_monthly(s, method, policy, months=range(6, 11)):
    """每月仅用月初之前 56 个完整日；H3 采用预先写定的分阶段网格。"""
    selected, all_scores = [], []
    for month in months:
        marker = s.cache / f"selection_{method}_{policy}_{month}.json"
        score_path = s.cache / f"selection_{method}_{policy}_{month}.csv"
        if marker.exists() and score_path.exists():
            selected.append(json.loads(marker.read_text())); all_scores.append(pd.read_csv(score_path)); continue
        origin = int(np.flatnonzero(s.dates == pd.Timestamp(2025, month, 1))[0])
        if policy == "H2_point":
            configs = [PolicyConfig(rho=float(r)) for r in RHO_GRID]
            scores = _score_configs(s, method, policy, origin, configs, "rho")
            winner = choose_near(scores, ["rho"])
        elif policy == "H3_quantile":
            coarse = [PolicyConfig(alpha=float(a), rho=.5, window=int(w), smooth=3)
                      for a in ALPHA_COARSE for w in WINDOW_GRID]
            a = _score_configs(s, method, policy, origin, coarse, "alpha_window")
            w1 = choose_near(a.assign(alpha_distance=np.abs(a.alpha - .8)),
                             ["alpha_distance", "window"])
            interaction = []
            fine = np.unique(np.round(np.clip(np.arange(w1.alpha - .04, w1.alpha + .041, .01), .5, .95), 2))
            for alpha in fine:
                for rho in RHO_GRID:
                    for smooth in SMOOTH_GRID:
                        interaction.append(PolicyConfig(float(alpha), float(rho), int(w1.window), int(smooth)))
            b = _score_configs(s, method, policy, origin, interaction, "local_interaction")
            b = b.assign(alpha_distance=np.abs(b.alpha - .8), rho_distance=np.abs(b.rho - .5))
            winner = choose_near(b, ["alpha_distance", "rho_distance", "smooth"])
            scores = pd.concat([a, b], ignore_index=True)
        elif policy == "H4_conditional":
            base = DEFAULT
            configs = [PolicyConfig(base["alpha"], float(r), 28, int(sm), f, int(k))
                       for f in FEATURE_GRID for k in K_GRID for r in RHO_GRID for sm in SMOOTH_GRID]
            scores = _score_configs(s, method, policy, origin, configs, "conditional")
            scores = scores.assign(rho_distance=np.abs(scores.rho - .5),
                                   feature_rank=scores.features.map({"season": 0, "weekday": 1, "level": 2}))
            winner = choose_near(scores, ["feature_rank", "k", "rho_distance", "smooth"])
        else:
            raise KeyError(policy)
        cfg = {k: (int(winner[k]) if k in ["window", "smooth", "k"] else
                   float(winner[k]) if k in ["alpha", "rho"] else winner[k])
               for k in PolicyConfig.__dataclass_fields__}
        record = {"method": method, "policy": policy, "month": month,
                  "origin": str(s.dates[origin].date()), "history_start": str(s.dates[origin - 56].date()),
                  "history_end": str(s.dates[origin - 1].date()), "score": float(winner.score), **cfg}
        atom_json(marker, record); scores.to_csv(score_path, index=False)
        selected.append(record); all_scores.append(scores)
        s.progress("selection_checkpoint", method=method, policy=policy, month=month, config=cfg)
    return pd.DataFrame(selected), pd.concat(all_scores, ignore_index=True)


def config_lookup(selection, default=DEFAULT):
    table = selection.set_index("month")
    def get(d):
        month = pd.Timestamp("2025-01-01") + pd.Timedelta(days=int(d))
        if month.month < 6:
            return PolicyConfig(**default)
        m = min(month.month, 10)
        return PolicyConfig(**{k: table.loc[m, k] for k in PolicyConfig.__dataclass_fields__})
    return get


def run_pilot(s):
    rows = []
    for method in s.fc:
        for policy in ["H0_fixed_SAA", "H1_fixedQ_causal", "H1_replan_SAA", "H2_point", "H3_quantile"]:
            frame, _ = s.simulate(method, policy, 151, 154, constant=PolicyConfig())
            rows.append({"method": method, "policy": policy, "cost": frame.total_cost.sum(),
                         "seconds": frame.solve_seconds.sum(), "checks_pass": bool(frame["pass"].all())})
    # 因果前缀测试：改变未来观测不应改变本槽 execute_step 的输出。
    q = np.full(T, 500.); ref = np.linspace(INITIAL, INITIAL, T + 1)
    actual = s.net_energy[151].copy(); changed = actual.copy(); changed[72:] += 1e6
    a = execute_causal(q, actual, INITIAL, ref, .5)
    b = execute_causal(q, changed, INITIAL, ref, .5)
    prefix_gap = max(np.max(np.abs(a[k][:72] - b[k][:72])) for k in ["c", "v", "z", "spill"])
    tests = {"all_checks_pass": all(r["checks_pass"] for r in rows),
             "future_perturbation_prefix_gap": float(prefix_gap),
             "information_boundary_pass": bool(prefix_gap < 1e-10)}
    if not tests["all_checks_pass"] or not tests["information_boundary_pass"]:
        raise AssertionError(tests)
    pd.DataFrame(rows).to_csv(s.out / "pilot.csv", index=False)
    atom_json(s.out / "pilot_tests.json", tests)
    s.progress("pilot_passed", tests=tests,
               estimated_seconds_per_policy_day=float(pd.DataFrame(rows).seconds.sum() / 45))
    return pd.DataFrame(rows), tests


def summarize_daily(s, daily):
    daily = daily.copy(); daily["date"] = pd.to_datetime(daily.date)
    periods = {"full334": ("2025-02-01", "2025-12-31"),
               "development153": ("2025-06-01", "2025-10-31"),
               "later61": ("2025-11-01", "2025-12-31")}
    rows = []
    for (method, policy), g in daily.groupby(["method", "policy"]):
        for period, (start, end) in periods.items():
            q = g[g.date.between(start, end)].sort_values("date")
            if len(q) != len(pd.date_range(start, end)):
                continue
            row = {"method": method, "policy": policy, "period": period, "days": len(q)}
            for col in ["planned_cost", "emergency_cost", "total_cost", "planned_kwh",
                        "emergency_kwh", "spill_kwh", "charge_kwh", "discharge_kwh",
                        "emergency_slots", "events", "solve_seconds"]:
                row[col] = float(q[col].sum())
            row.update({"start_soc": float(q.iloc[0].initial_soc),
                        "end_soc": float(q.iloc[-1].terminal_soc),
                        "inventory_adjusted_cost": inventory_adjusted_cost(q, s.price.min()),
                        "cvar90": cvar(q.total_cost, beta=.9), "cvar95": cvar(q.total_cost, beta=.95),
                        "max_daily_cost": float(q.total_cost.max()),
                        "emergency_day_frequency": float(q.emergency_day.mean()),
                        "emergency_slot_frequency": float(q.emergency_slots.sum() / (T * len(q)))})
            rows.append(row)
    return pd.DataFrame(rows)


def matched_oracles(s, summary):
    rows = []
    for _, r in summary[summary.period == "full334"].iterrows():
        terminal = float(r.end_soc)
        sol = s.base.solve(s.net[31:].reshape(1, -1), initial=INITIAL, terminal=terminal)
        oracle = s.base.realized(sol, s.net[31:].ravel(), take=334 * T)
        rows.append({"method": r.method, "policy": r.policy, "terminal_soc": terminal,
                     "actual_cost": r.total_cost, "oracle_cost": oracle["total_cost"],
                     "oracle_gap": r.total_cost - oracle["total_cost"],
                     "oracle_regret_rate": (r.total_cost - oracle["total_cost"]) / oracle["total_cost"],
                     "oracle_dual_gap_relative": sol["checks"]["dual_gap_relative"]})
    return pd.DataFrame(rows)


def bootstrap_against_h3(daily):
    rows = []
    daily = daily.copy(); daily["date"] = pd.to_datetime(daily.date)
    for method, g in daily.groupby("method"):
        base = g[g.policy == "H3_quantile"][["date", "total_cost"]].rename(columns={"total_cost": "base"})
        if base.empty:
            continue
        for policy, q in g.groupby("policy"):
            if policy == "H3_quantile":
                continue
            pair = q.merge(base, on="date")
            for period, start, end in [("development153", "2025-06-01", "2025-10-31"),
                                       ("later61", "2025-11-01", "2025-12-31")]:
                z = pair[pair.date.between(start, end)]
                if len(z) >= 7:
                    mean, lo, hi = bootstrap(z.base - z.total_cost, 7, 2000)
                    rows.append({"method": method, "policy": policy, "period": period,
                                 "saving_vs_H3_daily_mean": mean, "ci_low": lo, "ci_high": hi})
    return pd.DataFrame(rows)


def figures(s, summary, monthly, selection, daily, slots):
    import matplotlib.pyplot as plt
    import seaborn as sns
    plt.rcParams.update({"axes.unicode_minus": False, "pdf.fonttype": 42, "font.size": 10})
    manifest = []
    def emit(fig, name, meaning):
        for ext in ["pdf", "png"]:
            fig.savefig(s.fig / f"{name}.{ext}", bbox_inches="tight", dpi=180)
        plt.close(fig); manifest.append({"figure": name, "meaning": meaning})
    q = summary[summary.period == "development153"].copy()
    fig, ax = plt.subplots(figsize=(11, 5))
    pivot = q.pivot(index="method", columns="policy", values="total_cost") / 1e6
    pivot.plot.bar(ax=ax); ax.set_ylabel("Cost (million yuan)"); ax.set_xlabel("Forecast method")
    emit(fig, "hybrid_cost_comparison", "同一开发期比较固定执行、因果执行、点预测和分位数策略的总费用。")
    q = selection[selection.policy == "H3_quantile"]
    fig, ax = plt.subplots(figsize=(10, 5))
    for method, g in q.groupby("method"):
        ax.plot(g.month, g.alpha, marker="o", label=method)
    ax.axhline(.8, color="black", linestyle="--", label="economic anchor 0.8")
    ax.set(xlabel="Decision month", ylabel="Selected alpha", ylim=(.48, .97)); ax.legend()
    emit(fig, "selected_alpha_path", "逐月因果选择的分位数与0.8经济学锚点；变化反映误差分布和储能耦合。")
    fig, ax = plt.subplots(figsize=(11, 5))
    m = monthly.pivot_table(index="month", columns="policy", values="total_cost", aggfunc="sum") / 1e6
    m.plot(ax=ax, marker="o"); ax.set_ylabel("Monthly cost (million yuan)")
    emit(fig, "monthly_stability", "各策略月度总费用，检查结论是否由少数月份驱动。")
    if slots is not None and len(slots):
        example = slots[(slots.method == slots.method.iloc[0]) & (slots.policy == "H3_quantile")].iloc[:T]
        fig, ax = plt.subplots(figsize=(11, 5))
        ax.plot(example.slot, example.soc_start, label="actual SOC")
        ax.plot(example.slot, example.reference_soc_end, label="reference SOC", linestyle="--")
        ax.set(xlabel="10-minute slot", ylabel="SOC (kWh)"); ax.legend()
        emit(fig, "soc_causal_example", "实际SOC只由已发生误差更新，参考SOC仅用于形成保留线。")
    atom_json(s.fig / "figure_manifest.json", manifest)
    return pd.DataFrame(manifest)


def run_full(root):
    started = time.perf_counter(); s = HybridStudy(root)
    pilot, tests = run_pilot(s)
    selections, score_tables = [], []
    for method in s.fc:
        for policy in ["H2_point", "H3_quantile"]:
            selected, scores = select_monthly(s, method, policy)
            selections.append(selected); score_tables.append(scores)
    selection = pd.concat(selections, ignore_index=True)
    scores = pd.concat(score_tables, ignore_index=True)
    selection.to_csv(s.out / "selection.csv", index=False)
    scores.to_csv(s.out / "selection_scores.csv.gz", index=False, compression="gzip")
    daily_parts, slot_parts = [], []
    for method in s.fc:
        for policy in ["H0_fixed_SAA", "H1_fixedQ_causal", "H1_replan_SAA"]:
            frame, detail = s.simulate(method, policy, 31, 365, constant=PolicyConfig(), keep_slots=(policy == "H1_fixedQ_causal"))
            daily_parts.append(frame)
            if detail is not None: slot_parts.append(detail)
            s.progress("policy_checkpoint", method=method, policy=policy)
        for policy in ["H2_point", "H3_quantile"]:
            lookup = config_lookup(selection[(selection.method == method) & (selection.policy == policy)])
            frame, detail = s.simulate(method, policy, 31, 365, config_for_day=lookup, keep_slots=(policy == "H3_quantile"))
            daily_parts.append(frame)
            if detail is not None: slot_parts.append(detail)
            s.progress("policy_checkpoint", method=method, policy=policy)
    daily = pd.concat(daily_parts, ignore_index=True)
    # 只对开发期 H3 成本最低的预测模型运行条件策略，避免无价值的同质堆砌。
    provisional = summarize_daily(s, daily)
    best_method = provisional[(provisional.policy == "H3_quantile") &
                              (provisional.period == "development153")].sort_values("inventory_adjusted_cost").iloc[0].method
    cond_sel, cond_scores = select_monthly(s, best_method, "H4_conditional")
    selection = pd.concat([selection, cond_sel], ignore_index=True)
    scores = pd.concat([scores, cond_scores], ignore_index=True)
    lookup = config_lookup(cond_sel)
    frame, detail = s.simulate(best_method, "H4_conditional", 31, 365, config_for_day=lookup, keep_slots=True)
    daily = pd.concat([daily, frame], ignore_index=True); slot_parts.append(detail)
    slots = pd.concat(slot_parts, ignore_index=True)
    daily.to_csv(s.out / "daily.csv.gz", index=False, compression="gzip")
    slots.to_csv(s.out / "slots.csv.gz", index=False, compression="gzip")
    selection.to_csv(s.out / "selection.csv", index=False)
    scores.to_csv(s.out / "selection_scores.csv.gz", index=False, compression="gzip")
    summary = summarize_daily(s, daily); summary.to_csv(s.out / "summary.csv", index=False)
    monthly_source = daily.copy(); monthly_source["month"] = pd.to_datetime(monthly_source.date).dt.month
    monthly = monthly_source.groupby(["method", "policy", "month"], as_index=False)[
        ["planned_cost", "emergency_cost", "total_cost", "emergency_kwh", "spill_kwh"]].sum()
    monthly.to_csv(s.out / "monthly.csv", index=False)
    oracle = matched_oracles(s, summary); oracle.to_csv(s.out / "matched_oracles.csv", index=False)
    boot = bootstrap_against_h3(daily); boot.to_csv(s.out / "bootstrap.csv", index=False)
    checks = daily.groupby(["method", "policy"])[["balance_residual", "soc_recursion_residual",
        "simultaneous_max", "negative_min", "soc_min", "soc_max", "charge_max", "discharge_max"]].agg(
        {"balance_residual": "max", "soc_recursion_residual": "max", "simultaneous_max": "max",
         "negative_min": "min", "soc_min": "min", "soc_max": "max", "charge_max": "max", "discharge_max": "max"})
    checks.to_csv(s.out / "checks.csv")
    # 两个必须保留的回归证据：我方旧SAA精确复现；队友A移植结果只在实际跑完后判定。
    manual_h0 = summary[(summary.method == "ManualWeekly") & (summary.policy == "H0_fixed_SAA") &
                        (summary.period == "full334")].iloc[0].total_cost
    if abs(manual_h0 - 14539240.537931435) >= 1e-3:
        raise AssertionError((manual_h0, 14539240.537931435))
    team_fixed, _ = s.simulate("TeamA", "H3_quantile", 31, 365, constant=PolicyConfig(.8, .5, 28, 3))
    team_cost = float(team_fixed.total_cost.sum())
    regressions = {"legacy_saa_actual": manual_h0, "legacy_saa_reference": 14539240.537931435,
                   "team_a_port_actual": team_cost, "team_a_reference": 13820986.576531284,
                   "team_a_error": team_cost - 13820986.576531284}
    atom_json(s.out / "regressions.json", regressions)
    figs = figures(s, summary, monthly, selection, daily, slots)
    manifest = {"complete": True, "fingerprint": s.fingerprint, "best_h3_method": best_method,
                "rows": len(daily), "slots": len(slots), "runtime_seconds": time.perf_counter() - started,
                "checks_all_pass": bool(daily["pass"].all()), "pilot": tests,
                "official_result2_overwritten": False, "regressions": regressions,
                "parameter_protocol": "monthly causal 56-day calibration; Nov-Dec use Oct rule",
                "figure_count": len(figs)}
    atom_json(s.out / "manifest.json", manifest)
    s.progress("completed", runtime_seconds=manifest["runtime_seconds"], best_h3_method=best_method)
    return s, summary, monthly, selection, oracle, boot, figs, manifest


def render_results(s, summary, monthly, selection, oracle, boot, figs, manifest):
    """Notebook 最后一格调用；所有结论都从已运行结果生成，不预写优胜者。"""
    from IPython.display import Markdown, display
    display(Markdown("### 实验运行清单")); display(pd.DataFrame([manifest]))
    display(Markdown("### H0—H5费用与风险指标")); display(summary)
    display(Markdown("### 逐月因果选参")); display(selection)
    display(Markdown("### 匹配实际终态的Oracle下界")); display(oracle)
    display(Markdown("### 7日移动块Bootstrap")); display(boot)
    display(Markdown("### 图表含义登记")); display(figs)
    dev = summary[summary.period == "development153"].sort_values("inventory_adjusted_cost")
    later = summary[summary.period == "later61"].set_index(["method", "policy"])
    winner = dev.iloc[0]
    text = (f"开发期库存修正成本最低的是 **{winner.method} / {winner.policy}**，"
            f"费用为 {winner.inventory_adjusted_cost:,.2f} 元。其11—12月库存修正成本为 "
            f"{later.loc[(winner.method, winner.policy), 'inventory_adjusted_cost']:,.2f} 元。"
            "是否替换仍需结合Bootstrap区间、月度稳定性和结构复杂度判断；预测误差最低不自动等于成本最低。")
    display(Markdown(text))

## 8. Colab 小规模试运行、完整实验与检查点

先执行 3 日试运行和因果前缀测试；通过后自动进行逐月选参、334 日回测、匹配终态 Oracle、Bootstrap 和图表生成。所有阶段写入 `results/q2_hybrid_v1` 检查点，正式结果表不被覆盖。

In [ ]:
ROOT = PROJECT_ROOT
s, summary, monthly, selection, oracle, boot, figure_manifest, manifest = run_full(ROOT)

initialized {}

initialized {}

pilot_passed {'tests': {'all_checks_pass': True, 'future_perturbation_prefix_gap': 0.0, 'information_boundary_pass': True}, 'estimated_seconds_per_policy_day': 0.03120484546666881}

selection_checkpoint {'method': 'ManualWeekly', 'policy': 'H2_point', 'month': 6, 'config': {'alpha': 0.8, 'rho': 1.0, 'window': 28, 'smooth': 3, 'features': 'level', 'k': 21}}

selection_checkpoint {'method': 'ManualWeekly', 'policy': 'H2_point', 'month': 7, 'config': {'alpha': 0.8, 'rho': 1.0, 'window': 28, 'smooth': 3, 'features': 'level', 'k': 21}}

selection_checkpoint {'method': 'ManualWeekly', 'policy': 'H2_point', 'month': 8, 'config': {'alpha': 0.8, 'rho': 1.0, 'window': 28, 'smooth': 3, 'features': 'level', 'k': 21}}

selection_checkpoint {'method': 'ManualWeekly', 'policy': 'H2_point', 'month': 9, 'config': {'alpha': 0.8, 'rho': 1.0, 'window': 28, 'smooth': 3, 'features': 'level', 'k': 21}}

selection_checkpoint {'method': 'ManualWeekly', 'policy': 'H2_point', 'month': 10, 'config': {'alpha': 0.8, 'rho': 0.75, 'window': 28, 'smooth': 3, 'features': 'level', 'k': 21}}

selection_progress {'method': 'ManualWeekly', 'month': 6, 'stage': 'alpha_window', 'done': 20, 'total': 50}

selection_progress {'method': 'ManualWeekly', 'month': 6, 'stage': 'alpha_window', 'done': 40, 'total': 50}

selection_progress {'method': 'ManualWeekly', 'month': 6, 'stage': 'local_interaction', 'done': 20, 'total': 135}

selection_progress {'method': 'ManualWeekly', 'month': 6, 'stage': 'local_interaction', 'done': 40, 'total': 135}

selection_progress {'method': 'ManualWeekly', 'month': 6, 'stage': 'local_interaction', 'done': 60, 'total': 135}

selection_progress {'method': 'ManualWeekly', 'month': 6, 'stage': 'local_interaction', 'done': 80, 'total': 135}

selection_progress {'method': 'ManualWeekly', 'month': 6, 'stage': 'local_interaction', 'done': 100, 'total': 135}

selection_progress {'method': 'ManualWeekly', 'month': 6, 'stage': 'local_interaction', 'done': 120, 'total': 135}

selection_checkpoint {'method': 'ManualWeekly', 'policy': 'H3_quantile', 'month': 6, 'config': {'alpha': 0.8, 'rho': 0.5, 'window': 14, 'smooth': 0, 'features': 'level', 'k': 21}}

selection_progress {'method': 'ManualWeekly', 'month': 7, 'stage': 'alpha_window', 'done': 20, 'total': 50}

selection_progress {'method': 'ManualWeekly', 'month': 7, 'stage': 'alpha_window', 'done': 40, 'total': 50}

selection_progress {'method': 'ManualWeekly', 'month': 7, 'stage': 'local_interaction', 'done': 20, 'total': 135}

selection_progress {'method': 'ManualWeekly', 'month': 7, 'stage': 'local_interaction', 'done': 40, 'total': 135}

selection_progress {'method': 'ManualWeekly', 'month': 7, 'stage': 'local_interaction', 'done': 60, 'total': 135}

selection_progress {'method': 'ManualWeekly', 'month': 7, 'stage': 'local_interaction', 'done': 80, 'total': 135}

selection_progress {'method': 'ManualWeekly', 'month': 7, 'stage': 'local_interaction', 'done': 100, 'total': 135}

selection_progress {'method': 'ManualWeekly', 'month': 7, 'stage': 'local_interaction', 'done': 120, 'total': 135}

selection_checkpoint {'method': 'ManualWeekly', 'policy': 'H3_quantile', 'month': 7, 'config': {'alpha': 0.8, 'rho': 0.75, 'window': 14, 'smooth': 0, 'features': 'level', 'k': 21}}

selection_progress {'method': 'ManualWeekly', 'month': 8, 'stage': 'alpha_window', 'done': 20, 'total': 50}

selection_progress {'method': 'ManualWeekly', 'month': 8, 'stage': 'alpha_window', 'done': 40, 'total': 50}

selection_progress {'method': 'ManualWeekly', 'month': 8, 'stage': 'local_interaction', 'done': 20, 'total': 135}

selection_progress {'method': 'ManualWeekly', 'month': 8, 'stage': 'local_interaction', 'done': 40, 'total': 135}

selection_progress {'method': 'ManualWeekly', 'month': 8, 'stage': 'local_interaction', 'done': 60, 'total': 135}

selection_progress {'method': 'ManualWeekly', 'month': 8, 'stage': 'local_interaction', 'done': 80, 'total': 135}

selection_progress {'method': 'ManualWeekly', 'month': 8, 'stage': 'local_interaction', 'done': 100, 'total': 135}

selection_progress {'method': 'ManualWeekly', 'month': 8, 'stage': 'local_interaction', 'done': 120, 'total': 135}

selection_checkpoint {'method': 'ManualWeekly', 'policy': 'H3_quantile', 'month': 8, 'config': {'alpha': 0.8, 'rho': 0.25, 'window': 42, 'smooth': 0, 'features': 'level', 'k': 21}}

selection_progress {'method': 'ManualWeekly', 'month': 9, 'stage': 'alpha_window', 'done': 20, 'total': 50}

selection_progress {'method': 'ManualWeekly', 'month': 9, 'stage': 'alpha_window', 'done': 40, 'total': 50}

selection_progress {'method': 'ManualWeekly', 'month': 9, 'stage': 'local_interaction', 'done': 20, 'total': 135}

selection_progress {'method': 'ManualWeekly', 'month': 9, 'stage': 'local_interaction', 'done': 40, 'total': 135}

selection_progress {'method': 'ManualWeekly', 'month': 9, 'stage': 'local_interaction', 'done': 60, 'total': 135}

selection_progress {'method': 'ManualWeekly', 'month': 9, 'stage': 'local_interaction', 'done': 80, 'total': 135}

selection_progress {'method': 'ManualWeekly', 'month': 9, 'stage': 'local_interaction', 'done': 100, 'total': 135}

selection_progress {'method': 'ManualWeekly', 'month': 9, 'stage': 'local_interaction', 'done': 120, 'total': 135}

selection_checkpoint {'method': 'ManualWeekly', 'policy': 'H3_quantile', 'month': 9, 'config': {'alpha': 0.76, 'rho': 0.0, 'window': 14, 'smooth': 3, 'features': 'level', 'k': 21}}

selection_progress {'method': 'ManualWeekly', 'month': 10, 'stage': 'alpha_window', 'done': 20, 'total': 50}

selection_progress {'method': 'ManualWeekly', 'month': 10, 'stage': 'alpha_window', 'done': 40, 'total': 50}

selection_progress {'method': 'ManualWeekly', 'month': 10, 'stage': 'local_interaction', 'done': 20, 'total': 135}

selection_progress {'method': 'ManualWeekly', 'month': 10, 'stage': 'local_interaction', 'done': 40, 'total': 135}

selection_progress {'method': 'ManualWeekly', 'month': 10, 'stage': 'local_interaction', 'done': 60, 'total': 135}

selection_progress {'method': 'ManualWeekly', 'month': 10, 'stage': 'local_interaction', 'done': 80, 'total': 135}

selection_progress {'method': 'ManualWeekly', 'month': 10, 'stage': 'local_interaction', 'done': 100, 'total': 135}

selection_progress {'method': 'ManualWeekly', 'month': 10, 'stage': 'local_interaction', 'done': 120, 'total': 135}

selection_checkpoint {'method': 'ManualWeekly', 'policy': 'H3_quantile', 'month': 10, 'config': {'alpha': 0.81, 'rho': 0.25, 'window': 14, 'smooth': 0, 'features': 'level', 'k': 21}}

selection_checkpoint {'method': 'Ridge', 'policy': 'H2_point', 'month': 6, 'config': {'alpha': 0.8, 'rho': 1.0, 'window': 28, 'smooth': 3, 'features': 'level', 'k': 21}}

selection_checkpoint {'method': 'Ridge', 'policy': 'H2_point', 'month': 7, 'config': {'alpha': 0.8, 'rho': 1.0, 'window': 28, 'smooth': 3, 'features': 'level', 'k': 21}}

selection_checkpoint {'method': 'Ridge', 'policy': 'H2_point', 'month': 8, 'config': {'alpha': 0.8, 'rho': 1.0, 'window': 28, 'smooth': 3, 'features': 'level', 'k': 21}}

selection_checkpoint {'method': 'Ridge', 'policy': 'H2_point', 'month': 9, 'config': {'alpha': 0.8, 'rho': 0.0, 'window': 28, 'smooth': 3, 'features': 'level', 'k': 21}}

selection_checkpoint {'method': 'Ridge', 'policy': 'H2_point', 'month': 10, 'config': {'alpha': 0.8, 'rho': 0.75, 'window': 28, 'smooth': 3, 'features': 'level', 'k': 21}}

selection_progress {'method': 'Ridge', 'month': 6, 'stage': 'alpha_window', 'done': 20, 'total': 50}

selection_progress {'method': 'Ridge', 'month': 6, 'stage': 'alpha_window', 'done': 40, 'total': 50}

selection_progress {'method': 'Ridge', 'month': 6, 'stage': 'local_interaction', 'done': 20, 'total': 135}

selection_progress {'method': 'Ridge', 'month': 6, 'stage': 'local_interaction', 'done': 40, 'total': 135}

selection_progress {'method': 'Ridge', 'month': 6, 'stage': 'local_interaction', 'done': 60, 'total': 135}

selection_progress {'method': 'Ridge', 'month': 6, 'stage': 'local_interaction', 'done': 80, 'total': 135}

selection_progress {'method': 'Ridge', 'month': 6, 'stage': 'local_interaction', 'done': 100, 'total': 135}

selection_progress {'method': 'Ridge', 'month': 6, 'stage': 'local_interaction', 'done': 120, 'total': 135}

selection_checkpoint {'method': 'Ridge', 'policy': 'H3_quantile', 'month': 6, 'config': {'alpha': 0.8, 'rho': 0.5, 'window': 14, 'smooth': 0, 'features': 'level', 'k': 21}}

selection_progress {'method': 'Ridge', 'month': 7, 'stage': 'alpha_window', 'done': 20, 'total': 50}

selection_progress {'method': 'Ridge', 'month': 7, 'stage': 'alpha_window', 'done': 40, 'total': 50}

selection_progress {'method': 'Ridge', 'month': 7, 'stage': 'local_interaction', 'done': 20, 'total': 135}

selection_progress {'method': 'Ridge', 'month': 7, 'stage': 'local_interaction', 'done': 40, 'total': 135}

selection_progress {'method': 'Ridge', 'month': 7, 'stage': 'local_interaction', 'done': 60, 'total': 135}

selection_progress {'method': 'Ridge', 'month': 7, 'stage': 'local_interaction', 'done': 80, 'total': 135}

selection_progress {'method': 'Ridge', 'month': 7, 'stage': 'local_interaction', 'done': 100, 'total': 135}

selection_progress {'method': 'Ridge', 'month': 7, 'stage': 'local_interaction', 'done': 120, 'total': 135}

selection_checkpoint {'method': 'Ridge', 'policy': 'H3_quantile', 'month': 7, 'config': {'alpha': 0.8, 'rho': 0.5, 'window': 14, 'smooth': 0, 'features': 'level', 'k': 21}}

selection_progress {'method': 'Ridge', 'month': 8, 'stage': 'alpha_window', 'done': 20, 'total': 50}

selection_progress {'method': 'Ridge', 'month': 8, 'stage': 'alpha_window', 'done': 40, 'total': 50}

selection_progress {'method': 'Ridge', 'month': 8, 'stage': 'local_interaction', 'done': 20, 'total': 135}

selection_progress {'method': 'Ridge', 'month': 8, 'stage': 'local_interaction', 'done': 40, 'total': 135}

selection_progress {'method': 'Ridge', 'month': 8, 'stage': 'local_interaction', 'done': 60, 'total': 135}

selection_progress {'method': 'Ridge', 'month': 8, 'stage': 'local_interaction', 'done': 80, 'total': 135}

selection_progress {'method': 'Ridge', 'month': 8, 'stage': 'local_interaction', 'done': 100, 'total': 135}

selection_progress {'method': 'Ridge', 'month': 8, 'stage': 'local_interaction', 'done': 120, 'total': 135}

selection_checkpoint {'method': 'Ridge', 'policy': 'H3_quantile', 'month': 8, 'config': {'alpha': 0.74, 'rho': 0.0, 'window': 14, 'smooth': 0, 'features': 'level', 'k': 21}}

selection_progress {'method': 'Ridge', 'month': 9, 'stage': 'alpha_window', 'done': 20, 'total': 50}

selection_progress {'method': 'Ridge', 'month': 9, 'stage': 'alpha_window', 'done': 40, 'total': 50}

selection_progress {'method': 'Ridge', 'month': 9, 'stage': 'local_interaction', 'done': 20, 'total': 135}

selection_progress {'method': 'Ridge', 'month': 9, 'stage': 'local_interaction', 'done': 40, 'total': 135}

selection_progress {'method': 'Ridge', 'month': 9, 'stage': 'local_interaction', 'done': 60, 'total': 135}

selection_progress {'method': 'Ridge', 'month': 9, 'stage': 'local_interaction', 'done': 80, 'total': 135}

selection_progress {'method': 'Ridge', 'month': 9, 'stage': 'local_interaction', 'done': 100, 'total': 135}

selection_progress {'method': 'Ridge', 'month': 9, 'stage': 'local_interaction', 'done': 120, 'total': 135}

selection_checkpoint {'method': 'Ridge', 'policy': 'H3_quantile', 'month': 9, 'config': {'alpha': 0.76, 'rho': 0.25, 'window': 14, 'smooth': 3, 'features': 'level', 'k': 21}}

selection_progress {'method': 'Ridge', 'month': 10, 'stage': 'alpha_window', 'done': 20, 'total': 50}

selection_progress {'method': 'Ridge', 'month': 10, 'stage': 'alpha_window', 'done': 40, 'total': 50}

selection_progress {'method': 'Ridge', 'month': 10, 'stage': 'local_interaction', 'done': 20, 'total': 135}

selection_progress {'method': 'Ridge', 'month': 10, 'stage': 'local_interaction', 'done': 40, 'total': 135}

selection_progress {'method': 'Ridge', 'month': 10, 'stage': 'local_interaction', 'done': 60, 'total': 135}

selection_progress {'method': 'Ridge', 'month': 10, 'stage': 'local_interaction', 'done': 80, 'total': 135}

selection_progress {'method': 'Ridge', 'month': 10, 'stage': 'local_interaction', 'done': 100, 'total': 135}

selection_progress {'method': 'Ridge', 'month': 10, 'stage': 'local_interaction', 'done': 120, 'total': 135}

selection_checkpoint {'method': 'Ridge', 'policy': 'H3_quantile', 'month': 10, 'config': {'alpha': 0.83, 'rho': 0.25, 'window': 14, 'smooth': 5, 'features': 'level', 'k': 21}}

selection_checkpoint {'method': 'TeamA', 'policy': 'H2_point', 'month': 6, 'config': {'alpha': 0.8, 'rho': 0.75, 'window': 28, 'smooth': 3, 'features': 'level', 'k': 21}}

selection_checkpoint {'method': 'TeamA', 'policy': 'H2_point', 'month': 7, 'config': {'alpha': 0.8, 'rho': 1.0, 'window': 28, 'smooth': 3, 'features': 'level', 'k': 21}}

selection_checkpoint {'method': 'TeamA', 'policy': 'H2_point', 'month': 8, 'config': {'alpha': 0.8, 'rho': 0.75, 'window': 28, 'smooth': 3, 'features': 'level', 'k': 21}}

selection_checkpoint {'method': 'TeamA', 'policy': 'H2_point', 'month': 9, 'config': {'alpha': 0.8, 'rho': 0.75, 'window': 28, 'smooth': 3, 'features': 'level', 'k': 21}}

selection_checkpoint {'method': 'TeamA', 'policy': 'H2_point', 'month': 10, 'config': {'alpha': 0.8, 'rho': 1.0, 'window': 28, 'smooth': 3, 'features': 'level', 'k': 21}}

selection_progress {'method': 'TeamA', 'month': 6, 'stage': 'alpha_window', 'done': 20, 'total': 50}

selection_progress {'method': 'TeamA', 'month': 6, 'stage': 'alpha_window', 'done': 40, 'total': 50}

selection_progress {'method': 'TeamA', 'month': 6, 'stage': 'local_interaction', 'done': 20, 'total': 135}

selection_progress {'method': 'TeamA', 'month': 6, 'stage': 'local_interaction', 'done': 40, 'total': 135}

selection_progress {'method': 'TeamA', 'month': 6, 'stage': 'local_interaction', 'done': 60, 'total': 135}

selection_progress {'method': 'TeamA', 'month': 6, 'stage': 'local_interaction', 'done': 80, 'total': 135}

selection_progress {'method': 'TeamA', 'month': 6, 'stage': 'local_interaction', 'done': 100, 'total': 135}

selection_progress {'method': 'TeamA', 'month': 6, 'stage': 'local_interaction', 'done': 120, 'total': 135}

selection_checkpoint {'method': 'TeamA', 'policy': 'H3_quantile', 'month': 6, 'config': {'alpha': 0.76, 'rho': 0.5, 'window': 28, 'smooth': 0, 'features': 'level', 'k': 21}}

selection_progress {'method': 'TeamA', 'month': 7, 'stage': 'alpha_window', 'done': 20, 'total': 50}

selection_progress {'method': 'TeamA', 'month': 7, 'stage': 'alpha_window', 'done': 40, 'total': 50}

selection_progress {'method': 'TeamA', 'month': 7, 'stage': 'local_interaction', 'done': 20, 'total': 135}

selection_progress {'method': 'TeamA', 'month': 7, 'stage': 'local_interaction', 'done': 40, 'total': 135}

selection_progress {'method': 'TeamA', 'month': 7, 'stage': 'local_interaction', 'done': 60, 'total': 135}

selection_progress {'method': 'TeamA', 'month': 7, 'stage': 'local_interaction', 'done': 80, 'total': 135}

selection_progress {'method': 'TeamA', 'month': 7, 'stage': 'local_interaction', 'done': 100, 'total': 135}

selection_progress {'method': 'TeamA', 'month': 7, 'stage': 'local_interaction', 'done': 120, 'total': 135}

selection_checkpoint {'method': 'TeamA', 'policy': 'H3_quantile', 'month': 7, 'config': {'alpha': 0.8, 'rho': 0.75, 'window': 42, 'smooth': 0, 'features': 'level', 'k': 21}}

selection_progress {'method': 'TeamA', 'month': 8, 'stage': 'alpha_window', 'done': 20, 'total': 50}

selection_progress {'method': 'TeamA', 'month': 8, 'stage': 'alpha_window', 'done': 40, 'total': 50}

selection_progress {'method': 'TeamA', 'month': 8, 'stage': 'local_interaction', 'done': 20, 'total': 135}

selection_progress {'method': 'TeamA', 'month': 8, 'stage': 'local_interaction', 'done': 40, 'total': 135}

selection_progress {'method': 'TeamA', 'month': 8, 'stage': 'local_interaction', 'done': 60, 'total': 135}

selection_progress {'method': 'TeamA', 'month': 8, 'stage': 'local_interaction', 'done': 80, 'total': 135}

selection_progress {'method': 'TeamA', 'month': 8, 'stage': 'local_interaction', 'done': 100, 'total': 135}

selection_progress {'method': 'TeamA', 'month': 8, 'stage': 'local_interaction', 'done': 120, 'total': 135}

selection_checkpoint {'method': 'TeamA', 'policy': 'H3_quantile', 'month': 8, 'config': {'alpha': 0.77, 'rho': 0.0, 'window': 42, 'smooth': 0, 'features': 'level', 'k': 21}}

selection_progress {'method': 'TeamA', 'month': 9, 'stage': 'alpha_window', 'done': 20, 'total': 50}

selection_progress {'method': 'TeamA', 'month': 9, 'stage': 'alpha_window', 'done': 40, 'total': 50}

selection_progress {'method': 'TeamA', 'month': 9, 'stage': 'local_interaction', 'done': 20, 'total': 135}

selection_progress {'method': 'TeamA', 'month': 9, 'stage': 'local_interaction', 'done': 40, 'total': 135}

selection_progress {'method': 'TeamA', 'month': 9, 'stage': 'local_interaction', 'done': 60, 'total': 135}

selection_progress {'method': 'TeamA', 'month': 9, 'stage': 'local_interaction', 'done': 80, 'total': 135}

selection_progress {'method': 'TeamA', 'month': 9, 'stage': 'local_interaction', 'done': 100, 'total': 135}

selection_progress {'method': 'TeamA', 'month': 9, 'stage': 'local_interaction', 'done': 120, 'total': 135}

selection_checkpoint {'method': 'TeamA', 'policy': 'H3_quantile', 'month': 9, 'config': {'alpha': 0.75, 'rho': 0.25, 'window': 28, 'smooth': 0, 'features': 'level', 'k': 21}}

selection_progress {'method': 'TeamA', 'month': 10, 'stage': 'alpha_window', 'done': 20, 'total': 50}

selection_progress {'method': 'TeamA', 'month': 10, 'stage': 'alpha_window', 'done': 40, 'total': 50}

selection_progress {'method': 'TeamA', 'month': 10, 'stage': 'local_interaction', 'done': 20, 'total': 135}

selection_progress {'method': 'TeamA', 'month': 10, 'stage': 'local_interaction', 'done': 40, 'total': 135}

selection_progress {'method': 'TeamA', 'month': 10, 'stage': 'local_interaction', 'done': 60, 'total': 135}

selection_progress {'method': 'TeamA', 'month': 10, 'stage': 'local_interaction', 'done': 80, 'total': 135}

selection_progress {'method': 'TeamA', 'month': 10, 'stage': 'local_interaction', 'done': 100, 'total': 135}

selection_progress {'method': 'TeamA', 'month': 10, 'stage': 'local_interaction', 'done': 120, 'total': 135}

selection_checkpoint {'method': 'TeamA', 'policy': 'H3_quantile', 'month': 10, 'config': {'alpha': 0.82, 'rho': 0.75, 'window': 28, 'smooth': 0, 'features': 'level', 'k': 21}}

policy_checkpoint {'method': 'ManualWeekly', 'policy': 'H0_fixed_SAA'}

policy_checkpoint {'method': 'ManualWeekly', 'policy': 'H1_fixedQ_causal'}

policy_checkpoint {'method': 'ManualWeekly', 'policy': 'H1_replan_SAA'}

policy_checkpoint {'method': 'ManualWeekly', 'policy': 'H2_point'}

policy_checkpoint {'method': 'ManualWeekly', 'policy': 'H3_quantile'}

policy_checkpoint {'method': 'Ridge', 'policy': 'H0_fixed_SAA'}

policy_checkpoint {'method': 'Ridge', 'policy': 'H1_fixedQ_causal'}

policy_checkpoint {'method': 'Ridge', 'policy': 'H1_replan_SAA'}

policy_checkpoint {'method': 'Ridge', 'policy': 'H2_point'}

policy_checkpoint {'method': 'Ridge', 'policy': 'H3_quantile'}

policy_checkpoint {'method': 'TeamA', 'policy': 'H0_fixed_SAA'}

policy_checkpoint {'method': 'TeamA', 'policy': 'H1_fixedQ_causal'}

policy_checkpoint {'method': 'TeamA', 'policy': 'H1_replan_SAA'}

policy_checkpoint {'method': 'TeamA', 'policy': 'H2_point'}

policy_checkpoint {'method': 'TeamA', 'policy': 'H3_quantile'}

selection_progress {'method': 'Ridge', 'month': 6, 'stage': 'conditional', 'done': 20, 'total': 180}

selection_progress {'method': 'Ridge', 'month': 6, 'stage': 'conditional', 'done': 40, 'total': 180}

selection_progress {'method': 'Ridge', 'month': 6, 'stage': 'conditional', 'done': 60, 'total': 180}

selection_progress {'method': 'Ridge', 'month': 6, 'stage': 'conditional', 'done': 80, 'total': 180}

selection_progress {'method': 'Ridge', 'month': 6, 'stage': 'conditional', 'done': 100, 'total': 180}

selection_progress {'method': 'Ridge', 'month': 6, 'stage': 'conditional', 'done': 120, 'total': 180}

selection_progress {'method': 'Ridge', 'month': 6, 'stage': 'conditional', 'done': 140, 'total': 180}

selection_progress {'method': 'Ridge', 'month': 6, 'stage': 'conditional', 'done': 160, 'total': 180}

selection_progress {'method': 'Ridge', 'month': 6, 'stage': 'conditional', 'done': 180, 'total': 180}

selection_checkpoint {'method': 'Ridge', 'policy': 'H4_conditional', 'month': 6, 'config': {'alpha': 0.8, 'rho': 0.5, 'window': 28, 'smooth': 0, 'features': 'season', 'k': 14}}

selection_progress {'method': 'Ridge', 'month': 7, 'stage': 'conditional', 'done': 20, 'total': 180}

selection_progress {'method': 'Ridge', 'month': 7, 'stage': 'conditional', 'done': 40, 'total': 180}

selection_progress {'method': 'Ridge', 'month': 7, 'stage': 'conditional', 'done': 60, 'total': 180}

selection_progress {'method': 'Ridge', 'month': 7, 'stage': 'conditional', 'done': 80, 'total': 180}

selection_progress {'method': 'Ridge', 'month': 7, 'stage': 'conditional', 'done': 100, 'total': 180}

selection_progress {'method': 'Ridge', 'month': 7, 'stage': 'conditional', 'done': 120, 'total': 180}

selection_progress {'method': 'Ridge', 'month': 7, 'stage': 'conditional', 'done': 140, 'total': 180}

selection_progress {'method': 'Ridge', 'month': 7, 'stage': 'conditional', 'done': 160, 'total': 180}

selection_progress {'method': 'Ridge', 'month': 7, 'stage': 'conditional', 'done': 180, 'total': 180}

selection_checkpoint {'method': 'Ridge', 'policy': 'H4_conditional', 'month': 7, 'config': {'alpha': 0.8, 'rho': 0.5, 'window': 28, 'smooth': 0, 'features': 'season', 'k': 14}}

selection_progress {'method': 'Ridge', 'month': 8, 'stage': 'conditional', 'done': 20, 'total': 180}

selection_progress {'method': 'Ridge', 'month': 8, 'stage': 'conditional', 'done': 40, 'total': 180}

selection_progress {'method': 'Ridge', 'month': 8, 'stage': 'conditional', 'done': 60, 'total': 180}

selection_progress {'method': 'Ridge', 'month': 8, 'stage': 'conditional', 'done': 80, 'total': 180}

selection_progress {'method': 'Ridge', 'month': 8, 'stage': 'conditional', 'done': 100, 'total': 180}

selection_progress {'method': 'Ridge', 'month': 8, 'stage': 'conditional', 'done': 120, 'total': 180}

selection_progress {'method': 'Ridge', 'month': 8, 'stage': 'conditional', 'done': 140, 'total': 180}

selection_progress {'method': 'Ridge', 'month': 8, 'stage': 'conditional', 'done': 160, 'total': 180}

selection_progress {'method': 'Ridge', 'month': 8, 'stage': 'conditional', 'done': 180, 'total': 180}

selection_checkpoint {'method': 'Ridge', 'policy': 'H4_conditional', 'month': 8, 'config': {'alpha': 0.8, 'rho': 0.0, 'window': 28, 'smooth': 0, 'features': 'season', 'k': 14}}

selection_progress {'method': 'Ridge', 'month': 9, 'stage': 'conditional', 'done': 20, 'total': 180}

selection_progress {'method': 'Ridge', 'month': 9, 'stage': 'conditional', 'done': 40, 'total': 180}

selection_progress {'method': 'Ridge', 'month': 9, 'stage': 'conditional', 'done': 60, 'total': 180}

selection_progress {'method': 'Ridge', 'month': 9, 'stage': 'conditional', 'done': 80, 'total': 180}

selection_progress {'method': 'Ridge', 'month': 9, 'stage': 'conditional', 'done': 100, 'total': 180}

selection_progress {'method': 'Ridge', 'month': 9, 'stage': 'conditional', 'done': 120, 'total': 180}

selection_progress {'method': 'Ridge', 'month': 9, 'stage': 'conditional', 'done': 140, 'total': 180}

selection_progress {'method': 'Ridge', 'month': 9, 'stage': 'conditional', 'done': 160, 'total': 180}

selection_progress {'method': 'Ridge', 'month': 9, 'stage': 'conditional', 'done': 180, 'total': 180}

selection_checkpoint {'method': 'Ridge', 'policy': 'H4_conditional', 'month': 9, 'config': {'alpha': 0.8, 'rho': 0.25, 'window': 28, 'smooth': 0, 'features': 'season', 'k': 14}}

selection_progress {'method': 'Ridge', 'month': 10, 'stage': 'conditional', 'done': 20, 'total': 180}

selection_progress {'method': 'Ridge', 'month': 10, 'stage': 'conditional', 'done': 40, 'total': 180}

selection_progress {'method': 'Ridge', 'month': 10, 'stage': 'conditional', 'done': 60, 'total': 180}

selection_progress {'method': 'Ridge', 'month': 10, 'stage': 'conditional', 'done': 80, 'total': 180}

selection_progress {'method': 'Ridge', 'month': 10, 'stage': 'conditional', 'done': 100, 'total': 180}

selection_progress {'method': 'Ridge', 'month': 10, 'stage': 'conditional', 'done': 120, 'total': 180}

selection_progress {'method': 'Ridge', 'month': 10, 'stage': 'conditional', 'done': 140, 'total': 180}

selection_progress {'method': 'Ridge', 'month': 10, 'stage': 'conditional', 'done': 160, 'total': 180}

selection_progress {'method': 'Ridge', 'month': 10, 'stage': 'conditional', 'done': 180, 'total': 180}

selection_checkpoint {'method': 'Ridge', 'policy': 'H4_conditional', 'month': 10, 'config': {'alpha': 0.8, 'rho': 0.75, 'window': 28, 'smooth': 0, 'features': 'season', 'k': 14}}

completed {'runtime_seconds': 2593.649928349, 'best_h3_method': 'Ridge'}

## 9. 实验结果、图表含义与数据驱动结论

本单元格只读取刚刚实际计算的结果生成结论，不提前写入任何‘某模型最好’的判断。

In [ ]:
render_results(s, summary, monthly, selection, oracle, boot, figure_manifest, manifest)

### 实验运行清单

,complete,fingerprint,best_h3_method,rows,slots,runtime_seconds,checks_all_pass,pilot,official_result2_overwritten,regressions,parameter_protocol,figure_count
0,True,34182692e60b753665f6ee4fb7ff12a3271ce9c983ac0c...,Ridge,5344,336672,2593.649928,True,"{'all_checks_pass': True, 'future_perturbation...",False,"{'legacy_saa_actual': 14539240.537931435, 'leg...",monthly causal 56-day calibration; Nov-Dec use...,4

### H0—H5费用与风险指标

,method,policy,period,days,planned_cost,emergency_cost,total_cost,planned_kwh,emergency_kwh,spill_kwh,...,events,solve_seconds,start_soc,end_soc,inventory_adjusted_cost,cvar90,cvar95,max_daily_cost,emergency_day_frequency,emergency_slot_frequency
0,ManualWeekly,H0_fixed_SAA,full334,334,1.350133e+07,1.037912e+06,1.453924e+07,2.215128e+07,275365.941737,3.158995e+06,...,3748.0,15.736462,6000.000000,6000.000000,1.453924e+07,66664.754477,69594.287865,83541.886291,0.982036,0.191762
1,ManualWeekly,H0_fixed_SAA,development153,153,6.350942e+06,5.630866e+05,6.914029e+06,1.029600e+07,148320.346270,1.707576e+06,...,1534.0,7.051312,6000.000000,6000.000000,6.914029e+06,65247.130934,70853.372558,83541.886291,0.960784,0.189769
2,ManualWeekly,H0_fixed_SAA,later61,61,2.924912e+06,1.431465e+05,3.068058e+06,4.732522e+06,38872.936257,3.484557e+05,...,752.0,2.976753,6000.000000,6000.000000,3.068058e+06,69405.076210,72491.170955,76262.082828,1.000000,0.197974
3,ManualWeekly,H1_fixedQ_causal,full334,334,1.350133e+07,4.833688e+05,1.398470e+07,2.215128e+07,81199.833866,3.081921e+06,...,201.0,15.736462,6000.000000,6161.393330,1.398463e+07,66373.700474,70290.898052,86992.126751,0.341317,0.014263
4,ManualWeekly,H1_fixedQ_causal,development153,153,6.350942e+06,3.135291e+05,6.664471e+06,1.029600e+07,51864.505437,1.675858e+06,...,133.0,7.051312,7317.276592,6283.832662,6.664898e+06,64650.670512,71500.249857,86992.126751,0.437908,0.021196
5,ManualWeekly,H1_fixedQ_causal,later61,61,2.924912e+06,6.467966e+04,2.989591e+06,4.732522e+06,12590.807531,3.409707e+05,...,27.0,2.976753,6283.832662,6161.393330,2.989642e+06,69595.809476,73686.918815,79796.452186,0.245902,0.009791
6,ManualWeekly,H1_replan_SAA,full334,334,1.338822e+07,4.753976e+05,1.386362e+07,2.188748e+07,79352.753553,2.804736e+06,...,196.0,15.828102,6000.000000,6161.393330,1.386355e+07,66037.288229,70024.935874,90530.130893,0.341317,0.013847
7,ManualWeekly,H1_replan_SAA,development153,153,6.279738e+06,3.037499e+05,6.583488e+06,1.012994e+07,49770.140588,1.499496e+06,...,129.0,7.116249,7317.276592,6283.832662,6.583915e+06,63761.401578,70608.717504,90530.130893,0.437908,0.020470
8,ManualWeekly,H1_replan_SAA,later61,61,2.911809e+06,6.681936e+04,2.978629e+06,4.701867e+06,12989.945669,3.107765e+05,...,27.0,2.968559,6283.832662,6161.393330,2.978679e+06,69814.838772,74264.393303,80049.154385,0.245902,0.009904
9,ManualWeekly,H2_point,full334,334,1.218775e+07,3.119471e+06,1.530722e+07,2.012274e+07,609215.151189,1.555225e+06,...,1478.0,3.034202,6000.000000,5873.245108,1.530727e+07,83638.591317,93928.268045,119554.474217,0.886228,0.153755
10,ManualWeekly,H2_point,development153,153,5.604723e+06,1.722892e+06,7.327615e+06,9.130336e+06,370528.756637,8.150918e+05,...,1102.0,1.375503,6015.630148,6020.804835,7.327612e+06,87800.969588,98596.818401,119554.474217,0.921569,0.243464
11,ManualWeekly,H2_point,later61,61,2.636860e+06,8.531610e+05,3.490022e+06,4.308015e+06,152551.087558,5.398474e+04,...,202.0,0.561651,6020.804835,5873.245108,3.490082e+06,94041.852564,99560.351277,106131.166810,0.983607,0.154258
12,ManualWeekly,H3_quantile,full334,334,1.324073e+07,6.927588e+05,1.393349e+07,2.164724e+07,117911.276337,2.592299e+06,...,217.0,3.008385,6000.000000,6130.955243,1.393344e+07,67459.107147,72222.706556,96801.960616,0.353293,0.018900
13,ManualWeekly,H3_quantile,development153,153,6.214699e+06,4.410313e+05,6.655730e+06,1.002057e+07,75229.497333,1.410382e+06,...,136.0,1.365550,7755.244734,6267.174485,6.656344e+06,65956.032205,75230.243039,96801.960616,0.411765,0.028413
14,ManualWeekly,H3_quantile,later61,61,2.890642e+06,7.912287e+04,2.969765e+06,4.670841e+06,15399.832606,2.803022e+05,...,32.0,0.559157,6267.174485,6130.955243,2.969821e+06,71262.524368,76346.048928,81888.328428,0.295082,0.010018
15,Ridge,H0_fixed_SAA,full334,334,1.340781e+07,9.793044e+05,1.438711e+07,2.201956e+07,260668.479475,3.016046e+06,...,3985.0,15.802774,6000.000000,6000.000000,1.438711e+07,64626.537581,66210.561022,76888.762036,0.997006,0.194424
16,Ridge,H0_fixed_SAA,development153,153,6.271097e+06,5.201694e+05,6.791267e+06,1.018646e+07,137668.987989,1.589561e+06,...,1764.0,7.076304,6000.000000,6000.000000,6.791267e+06,62267.230095,65403.630951,76888.762036,0.993464,0.198802
17,Ridge,H0_fixed_SAA,later61,61,2.924600e+06,1.158782e+05,3.040478e+06,4.730433e+06,31446.302040,3.393056e+05,...,776.0,2.998183,6000.000000,6000.000000,3.040478e+06,66355.936858,67395.083310,69539.971506,1.000000,0.178848
18,Ridge,H1_fixedQ_causal,full334,334,1.340781e+07,3.527972e+05,1.376061e+07,2.201956e+07,57130.308771,2.918270e+06,...,193.0,15.802774,6000.000000,6069.933521,1.376058e+07,63317.025241,65740.813794,81328.344020,0.350299,0.010999
19,Ridge,H1_fixedQ_causal,development153,153,6.271097e+06,2.089262e+05,6.480023e+06,1.018646e+07,33516.708113,1.541850e+06,...,133.0,7.076304,7435.284268,6144.526913,6.480556e+06,60332.199524,63787.428098,81328.344020,0.470588,0.015432
20,Ridge,H1_fixedQ_causal,later61,61,2.924600e+06,1.951575e+04,2.944116e+06,4.730433e+06,3944.392957,3.288814e+05,...,17.0,2.998183,6144.526913,6069.933521,2.944147e+06,65439.195330,66421.333784,69920.490306,0.196721,0.004668
21,Ridge,H1_replan_SAA,full334,334,1.331076e+07,3.566843e+05,1.366744e+07,2.179308e+07,57851.696272,2.684083e+06,...,193.0,15.903517,6000.000000,6069.933521,1.366741e+07,63156.118502,65682.590069,83280.629027,0.353293,0.011061
22,Ridge,H1_replan_SAA,development153,153,6.217861e+06,2.061158e+05,6.423977e+06,1.006225e+07,33044.277277,1.411502e+06,...,133.0,7.129966,7435.284268,6144.526913,6.424509e+06,59972.085467,63590.045089,83280.629027,0.477124,0.015341
23,Ridge,H1_replan_SAA,later61,61,2.908444e+06,2.311680e+04,2.931561e+06,4.692630e+06,4655.077188,2.919209e+05,...,17.0,2.988182,6144.526913,6069.933521,2.931592e+06,65742.274628,67189.810330,71629.847652,0.196721,0.005009
24,Ridge,H2_point,full334,334,1.206873e+07,4.135347e+06,1.620408e+07,1.990296e+07,768374.696613,1.514632e+06,...,1367.0,3.022303,6000.000000,5743.796530,1.620418e+07,84642.830317,92204.265396,117048.966050,0.904192,0.165170
25,Ridge,H2_point,development153,153,5.609546e+06,1.950522e+06,7.560068e+06,9.119140e+06,393652.507341,8.341168e+05,...,928.0,1.367632,6253.221023,5643.225684,7.560319e+06,88364.887211,96739.335599,117048.966050,0.915033,0.221178
26,Ridge,H2_point,later61,61,2.565345e+06,1.296511e+06,3.861856e+06,4.213622e+06,230594.073716,4.207969e+04,...,232.0,0.562404,5643.225684,5743.796530,3.861814e+06,90321.747429,96315.359187,100464.967282,1.000000,0.232582
27,Ridge,H3_quantile,full334,334,1.310006e+07,6.103494e+05,1.371041e+07,2.145072e+07,99102.253654,2.371134e+06,...,240.0,3.054543,6000.000000,6097.805150,1.371037e+07,64786.863874,67501.473278,88659.791637,0.419162,0.016509
28,Ridge,H3_quantile,development153,153,6.077696e+06,3.703157e+05,6.448012e+06,9.838381e+06,59797.256387,1.205195e+06,...,165.0,1.386589,7795.048902,6136.367266,6.448696e+06,63053.321969,69158.087287,88659.791637,0.562092,0.023239
29,Ridge,H3_quantile,later61,61,2.901211e+06,2.463585e+04,2.925847e+06,4.681516e+06,5016.659870,2.805242e+05,...,16.0,0.568643,6136.367266,6097.805150,2.925863e+06,65818.786295,67149.049053,71281.763485,0.213115,0.004668
30,Ridge,H4_conditional,full334,334,1.308680e+07,5.904611e+05,1.367726e+07,2.144361e+07,96408.292864,2.357709e+06,...,251.0,3.066559,6000.000000,6037.745342,1.367724e+07,64142.927821,66793.091058,88657.547651,0.440120,0.017403
31,Ridge,H4_conditional,development153,153,6.105024e+06,3.305188e+05,6.435543e+06,9.882337e+06,53692.652793,1.243430e+06,...,157.0,1.389348,7668.430078,6049.766442,6.436210e+06,62058.616057,67239.553308,88657.547651,0.535948,0.022286
32,Ridge,H4_conditional,later61,61,2.884435e+06,3.227037e+04,2.916705e+06,4.659271e+06,6336.257854,2.579865e+05,...,25.0,0.567657,6049.766442,6037.745342,2.916710e+06,65907.878451,67664.959236,72512.008549,0.295082,0.008083
33,TeamA,H0_fixed_SAA,full334,334,1.347890e+07,1.049058e+06,1.452796e+07,2.212327e+07,276498.412032,3.134912e+06,...,3712.0,15.888064,6000.000000,6000.000000,1.452796e+07,66940.802928,69512.116085,87052.381419,0.991018,0.188498
34,TeamA,H0_fixed_SAA,development153,153,6.318324e+06,5.808148e+05,6.899139e+06,1.025441e+07,151612.004433,1.670790e+06,...,1560.0,7.118517,6000.000000,6000.000000,6.899139e+06,66732.546993,71918.325525,87052.381419,0.980392,0.185231
35,TeamA,H0_fixed_SAA,later61,61,2.927089e+06,1.398486e+05,3.066938e+06,4.736618e+06,37551.392035,3.510744e+05,...,771.0,2.988143,6000.000000,6000.000000,3.066938e+06,68410.001333,70810.395523,75131.617060,1.000000,0.195924
36,TeamA,H1_fixedQ_causal,full334,334,1.347890e+07,4.724545e+05,1.395135e+07,2.212327e+07,77722.608421,3.050067e+06,...,238.0,15.888064,6000.000000,6192.482309,1.395127e+07,66056.755383,69909.618289,91255.975750,0.386228,0.014222
37,TeamA,H1_fixedQ_causal,development153,153,6.318324e+06,3.126771e+05,6.631001e+06,1.025441e+07,51055.182666,1.630383e+06,...,148.0,7.118517,6693.693840,7007.139490,6.630872e+06,66322.153124,72848.276283,91255.975750,0.450980,0.020652
38,TeamA,H1_fixedQ_causal,later61,61,2.927089e+06,4.823081e+04,2.975320e+06,4.736618e+06,9137.597613,3.414090e+05,...,28.0,2.988143,7007.139490,6192.482309,2.975656e+06,68721.393611,72295.969392,80157.514360,0.327869,0.008424
39,TeamA,H1_replan_SAA,full334,334,1.336750e+07,4.692518e+05,1.383675e+07,2.186341e+07,76932.603353,2.777999e+06,...,236.0,15.979058,6000.000000,6192.482309,1.383667e+07,65892.214206,69778.068258,93993.225132,0.386228,0.013847
40,TeamA,H1_replan_SAA,development153,153,6.255063e+06,3.080849e+05,6.563148e+06,1.010677e+07,50036.290245,1.474442e+06,...,145.0,7.162639,6693.693840,7007.139490,6.563019e+06,65864.550957,72657.802107,93993.225132,0.450980,0.019926
41,TeamA,H1_replan_SAA,later61,61,2.910997e+06,4.979460e+04,2.960791e+06,4.698930e+06,9427.523252,3.040500e+05,...,30.0,3.023323,7007.139490,6192.482309,2.961127e+06,68774.658095,72676.204973,81377.964230,0.327869,0.008652
42,TeamA,H2_point,full334,334,1.219130e+07,2.773714e+06,1.496502e+07,2.014182e+07,518137.537341,1.466779e+06,...,1730.0,3.087970,6000.000000,5985.242039,1.496502e+07,77539.219838,85818.750236,123565.175859,0.886228,0.154753
43,TeamA,H2_point,development153,153,5.605976e+06,1.671170e+06,7.277146e+06,9.155013e+06,313837.942932,7.752395e+05,...,833.0,1.399529,6137.992598,6298.543537,7.277080e+06,84513.013196,92989.469634,123565.175859,0.921569,0.186638
44,TeamA,H2_point,later61,61,2.699606e+06,4.309528e+05,3.130558e+06,4.409222e+06,95049.006101,9.346580e+04,...,683.0,0.576332,6298.543537,5985.242039,3.130688e+06,75138.755414,81621.931852,89353.045049,1.000000,0.276867
45,TeamA,H3_quantile,full334,334,1.319793e+07,6.411142e+05,1.383905e+07,2.158275e+07,106557.609597,2.516245e+06,...,244.0,3.104264,6000.000000,6182.341529,1.383897e+07,67181.308262,71297.382742,103524.709658,0.413174,0.018629
46,TeamA,H3_quantile,development153,153,6.135330e+06,4.388625e+05,6.574192e+06,9.912867e+06,72491.781823,1.295456e+06,...,145.0,1.405310,6989.860069,7014.742470,6.574182e+06,68511.084644,76220.474058,103524.709658,0.483660,0.026325
47,TeamA,H3_quantile,later61,61,2.917196e+06,4.990730e+04,2.967104e+06,4.704642e+06,9620.775855,3.105651e+05,...,25.0,0.575063,7014.742470,6182.341529,2.967447e+06,68533.080130,72540.406616,80587.340799,0.295082,0.010360

### 逐月因果选参

,method,policy,month,origin,history_start,history_end,score,alpha,rho,window,smooth,features,k
0,ManualWeekly,H2_point,6,2025-06-01,2025-04-06,2025-05-31,1.957590e+06,0.80,1.00,28,3,level,21
1,ManualWeekly,H2_point,7,2025-07-01,2025-05-06,2025-06-30,2.669451e+06,0.80,1.00,28,3,level,21
2,ManualWeekly,H2_point,8,2025-08-01,2025-06-06,2025-07-31,3.096096e+06,0.80,1.00,28,3,level,21
3,ManualWeekly,H2_point,9,2025-09-01,2025-07-07,2025-08-31,2.729163e+06,0.80,1.00,28,3,level,21
4,ManualWeekly,H2_point,10,2025-10-01,2025-08-06,2025-09-30,2.270378e+06,0.80,0.75,28,3,level,21
5,ManualWeekly,H3_quantile,6,2025-06-01,2025-04-06,2025-05-31,1.797548e+06,0.80,0.50,14,0,level,21
6,ManualWeekly,H3_quantile,7,2025-07-01,2025-05-06,2025-06-30,2.270635e+06,0.80,0.75,14,0,level,21
7,ManualWeekly,H3_quantile,8,2025-08-01,2025-06-06,2025-07-31,2.632184e+06,0.80,0.25,42,0,level,21
8,ManualWeekly,H3_quantile,9,2025-09-01,2025-07-07,2025-08-31,2.461414e+06,0.76,0.00,14,3,level,21
9,ManualWeekly,H3_quantile,10,2025-10-01,2025-08-06,2025-09-30,2.219499e+06,0.81,0.25,14,0,level,21
10,Ridge,H2_point,6,2025-06-01,2025-04-06,2025-05-31,2.151019e+06,0.80,1.00,28,3,level,21
11,Ridge,H2_point,7,2025-07-01,2025-05-06,2025-06-30,2.892282e+06,0.80,1.00,28,3,level,21
12,Ridge,H2_point,8,2025-08-01,2025-06-06,2025-07-31,2.980709e+06,0.80,1.00,28,3,level,21
13,Ridge,H2_point,9,2025-09-01,2025-07-07,2025-08-31,2.481884e+06,0.80,0.00,28,3,level,21
14,Ridge,H2_point,10,2025-10-01,2025-08-06,2025-09-30,2.319944e+06,0.80,0.75,28,3,level,21
15,Ridge,H3_quantile,6,2025-06-01,2025-04-06,2025-05-31,1.788780e+06,0.80,0.50,14,0,level,21
16,Ridge,H3_quantile,7,2025-07-01,2025-05-06,2025-06-30,2.217047e+06,0.80,0.50,14,0,level,21
17,Ridge,H3_quantile,8,2025-08-01,2025-06-06,2025-07-31,2.554770e+06,0.74,0.00,14,0,level,21
18,Ridge,H3_quantile,9,2025-09-01,2025-07-07,2025-08-31,2.451235e+06,0.76,0.25,14,3,level,21
19,Ridge,H3_quantile,10,2025-10-01,2025-08-06,2025-09-30,2.201609e+06,0.83,0.25,14,5,level,21
20,TeamA,H2_point,6,2025-06-01,2025-04-06,2025-05-31,1.920823e+06,0.80,0.75,28,3,level,21
21,TeamA,H2_point,7,2025-07-01,2025-05-06,2025-06-30,2.433446e+06,0.80,1.00,28,3,level,21
22,TeamA,H2_point,8,2025-08-01,2025-06-06,2025-07-31,2.763100e+06,0.80,0.75,28,3,level,21
23,TeamA,H2_point,9,2025-09-01,2025-07-07,2025-08-31,2.609211e+06,0.80,0.75,28,3,level,21
24,TeamA,H2_point,10,2025-10-01,2025-08-06,2025-09-30,2.569681e+06,0.80,1.00,28,3,level,21
25,TeamA,H3_quantile,6,2025-06-01,2025-04-06,2025-05-31,1.791959e+06,0.76,0.50,28,0,level,21
26,TeamA,H3_quantile,7,2025-07-01,2025-05-06,2025-06-30,2.229166e+06,0.80,0.75,42,0,level,21
27,TeamA,H3_quantile,8,2025-08-01,2025-06-06,2025-07-31,2.601582e+06,0.77,0.00,42,0,level,21
28,TeamA,H3_quantile,9,2025-09-01,2025-07-07,2025-08-31,2.479466e+06,0.75,0.25,28,0,level,21
29,TeamA,H3_quantile,10,2025-10-01,2025-08-06,2025-09-30,2.253408e+06,0.82,0.75,28,0,level,21
30,Ridge,H4_conditional,6,2025-06-01,2025-04-06,2025-05-31,1.788780e+06,0.80,0.50,28,0,season,14
31,Ridge,H4_conditional,7,2025-07-01,2025-05-06,2025-06-30,2.217047e+06,0.80,0.50,28,0,season,14
32,Ridge,H4_conditional,8,2025-08-01,2025-06-06,2025-07-31,2.569030e+06,0.80,0.00,28,0,season,14
33,Ridge,H4_conditional,9,2025-09-01,2025-07-07,2025-08-31,2.464811e+06,0.80,0.25,28,0,season,14
34,Ridge,H4_conditional,10,2025-10-01,2025-08-06,2025-09-30,2.204748e+06,0.80,0.75,28,0,season,14

### 匹配实际终态的Oracle下界

,method,policy,terminal_soc,actual_cost,oracle_cost,oracle_gap,oracle_regret_rate,oracle_dual_gap_relative
0,ManualWeekly,H0_fixed_SAA,6000.000000,1.453924e+07,1.223038e+07,2.308857e+06,0.188780,4.568896e-16
1,ManualWeekly,H1_fixedQ_causal,6161.393330,1.398470e+07,1.223046e+07,1.754237e+06,0.143432,3.045912e-16
2,ManualWeekly,H1_replan_SAA,6161.393330,1.386362e+07,1.223046e+07,1.633160e+06,0.133532,3.045912e-16
3,ManualWeekly,H2_point,5873.245108,1.530722e+07,1.223032e+07,3.076894e+06,0.251579,4.568919e-16
4,ManualWeekly,H3_quantile,6130.955243,1.393349e+07,1.223045e+07,1.703047e+06,0.139247,4.568873e-16
5,Ridge,H0_fixed_SAA,6000.000000,1.438711e+07,1.223038e+07,2.156731e+06,0.176342,4.568896e-16
6,Ridge,H1_fixedQ_causal,6069.933521,1.376061e+07,1.223042e+07,1.530190e+06,0.125114,4.568884e-16
7,Ridge,H1_replan_SAA,6069.933521,1.366744e+07,1.223042e+07,1.437025e+06,0.117496,4.568884e-16
8,Ridge,H2_point,5743.796530,1.620408e+07,1.223026e+07,3.973815e+06,0.324917,3.045961e-16
9,Ridge,H3_quantile,6097.805150,1.371041e+07,1.223043e+07,1.479978e+06,0.121008,6.091839e-16
10,Ridge,H4_conditional,6037.745342,1.367726e+07,1.223040e+07,1.446858e+06,0.118300,4.568890e-16
11,TeamA,H0_fixed_SAA,6000.000000,1.452796e+07,1.223038e+07,2.297573e+06,0.187858,4.568896e-16
12,TeamA,H1_fixedQ_causal,6192.482309,1.395135e+07,1.223047e+07,1.720879e+06,0.140704,3.045908e-16
13,TeamA,H1_replan_SAA,6192.482309,1.383675e+07,1.223047e+07,1.606273e+06,0.131334,3.045908e-16
14,TeamA,H2_point,5985.242039,1.496502e+07,1.223038e+07,2.734642e+06,0.223594,3.045933e-16
15,TeamA,H3_quantile,6182.341529,1.383905e+07,1.223047e+07,1.608576e+06,0.131522,3.045909e-16

### 7日移动块Bootstrap

,method,policy,period,saving_vs_H3_daily_mean,ci_low,ci_high
0,ManualWeekly,H0_fixed_SAA,development153,-1688.223861,-2410.404950,-1221.152165
1,ManualWeekly,H0_fixed_SAA,later61,-1611.368095,-1999.196403,-1144.608411
2,ManualWeekly,H1_fixedQ_causal,development153,-57.128995,-796.127011,533.898295
3,ManualWeekly,H1_fixedQ_causal,later61,-325.027022,-669.340094,148.548220
4,ManualWeekly,H1_replan_SAA,development153,472.170471,-161.601355,1003.378050
5,ManualWeekly,H1_replan_SAA,later61,-145.311954,-435.251218,250.020580
6,ManualWeekly,H2_point,development153,-4391.398958,-6726.731909,-1619.392864
7,ManualWeekly,H2_point,later61,-8528.798936,-14919.550819,-4512.403943
8,Ridge,H0_fixed_SAA,development153,-2243.496127,-2814.716094,-1796.429668
9,Ridge,H0_fixed_SAA,later61,-1879.203127,-2199.436202,-1601.535567
10,Ridge,H1_fixedQ_causal,development153,-209.226659,-829.282458,375.163389
11,Ridge,H1_fixedQ_causal,later61,-299.490895,-462.222667,-125.531622
12,Ridge,H1_replan_SAA,development153,157.090762,-396.917335,708.980729
13,Ridge,H1_replan_SAA,later61,-93.669442,-240.566079,47.828362
14,Ridge,H2_point,development153,-7268.339947,-9943.796081,-3767.547890
15,Ridge,H2_point,later61,-15344.405973,-18965.470290,-13315.175381
16,Ridge,H4_conditional,development153,81.497198,-83.687428,299.939712
17,Ridge,H4_conditional,later61,149.869120,-3.230863,252.462336
18,TeamA,H0_fixed_SAA,development153,-2123.833039,-2849.175210,-1697.730339
19,TeamA,H0_fixed_SAA,later61,-1636.629408,-1893.775675,-1350.152394
20,TeamA,H1_fixedQ_causal,development153,-371.299136,-1060.675826,204.941834
21,TeamA,H1_fixedQ_causal,later61,-134.697799,-387.720040,112.792289
22,TeamA,H1_replan_SAA,development153,72.183167,-541.128595,559.814445
23,TeamA,H1_replan_SAA,later61,103.480280,-143.533147,339.983392
24,TeamA,H2_point,development153,-4594.468550,-6093.244161,-2707.821551
25,TeamA,H2_point,later61,-2679.585712,-4402.926366,-872.073781

### 图表含义登记

                   figure                             meaning
0  hybrid_cost_comparison     同一开发期比较固定执行、因果执行、点预测和分位数策略的总费用。
1     selected_alpha_path  逐月因果选择的分位数与0.8经济学锚点；变化反映误差分布和储能耦合。
2       monthly_stability             各策略月度总费用，检查结论是否由少数月份驱动。
3      soc_causal_example       实际SOC只由已发生误差更新，参考SOC仅用于形成保留线。

开发期库存修正成本最低的是 **Ridge / H1_replan_SAA**，费用为 6,424,509.34 元。其11—12月库存修正成本为 2,931,591.70 元。是否替换仍需结合Bootstrap区间、月度稳定性和结构复杂度判断；预测误差最低不自动等于成本最低。